### ISSUE TITLE
Keepass windows unresponsive if password generator was used in browser

### ISSUE THREAD

**Issue by dias-yelgonov** [keepassxreboot/keepassxc#10168]
## Overview
The Keepass window becomes unresponsive in Windows if you try to close the password generator using the Windows "X" button, on the top of the right corner, of "Close" option next to "Apply Password".
Windows produces audio sound, similar to active prompt windows. Even, if there is no active prompt in the background or the list of processes in Task Manager.
I found a similar bug in history: 
https://github.com/keepassxreboot/keepassxc/issues/7952

## Steps to Reproduce
1. Open any web page and open context-menu using right-click
3. Choose KeepassXC-Browser -> Show Password Generator
4. Close it using "X" button of the window.
5. To remove the unresponsive condition, open the password generator again
6. Finish the process using the "Close" button

## Expected Behavior
Once you close password generator, the main UI continues to operate

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro 22H2
OS Build: 19045.3803

**Comment by droidmonkey** [comment]
Use the close button in the window, we fixed this and will be part of 2.7.7

**Comment by Tidone** [comment]
Hi @droidmonkey,
can you reopen this issue, as it's still not fixed in 2.7.7, or should I open a new issue?

**Comment by dias-yelgonov** [comment]
> Hi @droidmonkey, can you reopen this issue, as it's still not fixed in 2.7.7, or should I open a new issue?

For me the issue still persist as well, even after update to 2.7.7

**Comment by droidmonkey** [comment]
hmmm I don't think we backported the correct fix...

**Comment by droidmonkey** [comment]
Closed in 485c446013a2b488fd35b3a7b4022a2f4dc92d8f
