### ISSUE TITLE
Add wl-clipboard to Flatpak

### ISSUE THREAD

**Issue by DPTJKKVH** [keepassxreboot/keepassxc#11292]
## Overview
When copying a password with CTRL + C the password is only cleared after the countdown if the KeepassXC window is in focus. If it is out of focus, the password remains in the clipboard indefinitely.

## Steps to Reproduce
1. Click on a database entry.
2. CTRL + C to copy the password
3. Highlight a different window than the KeepassXC window. (e.g. a text editor)
4. Wait until the "clear clipboard after" timer runs out.
5. CTRL + V in the different window.

## Expected Behavior
No password should be pasted since it should have been cleared form the clipboard after the timer ran out.

## Actual Behavior
The password can still be pasted.

## Context
Here is a video of the bug.
[keepassxc_bug.webm](https://github.com/user-attachments/assets/179afa42-a80a-4bee-bd67-fab388c2cc38)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap
Qt 5.15.11
Operating System: Ubuntu 22.04.5 LTS
Desktop Env: Gnome 42.9
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This was fixed in 2.7.9

**Comment by DPTJKKVH** [comment]
@droidmonkey

Please reopen this issue. I tried it with the 2.7.9 Flatpak version and the issue still persists. Video below!
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak
Qt 5.15.10

**Video**
[keepassxcbugwithflatpak.webm](https://github.com/user-attachments/assets/0085908b-e99c-4bfc-b4e9-d7d6979bc604)

**Comment by droidmonkey** [comment]
This isn't our bug. It's a bug/feature of GNOME on Wayland. We try to work around it by calling wlcopy directly instead of through Qt. Unfortunately we can't do that with Flatpak.

**Comment by DPTJKKVH** [comment]
Understood. Why is the Snap version still on 2.7.8 on the stable branch though? Is that deliberate?

**Comment by droidmonkey** [comment]
The snap owners have our update held up in some manual review. The whole process with snaps is broken.

**Comment by DPTJKKVH** [comment]
Thank you for answering my questions and maintaining this project despite the many challenges it poses. Fully understood and I will move on to the PPA then.

**Comment by droidmonkey** [comment]
@DPTJKKVH you may have to install wl-clipboard if you haven't already even with the ppa.

**Comment by DPTJKKVH** [comment]
@droidmonkey

fyi: I didn't need to install wl-clipboard for the clipboard clearing to work as intended. (I verified in synaptic that it isn't installed.) Just in case that information is useful.

**Comment by droidmonkey** [comment]
I'm going to try to add wl-clipboard to the flatpak itself, see if that works

**Comment by DPTJKKVH** [comment]
I have an interesting update to this:

KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Launchpad PPA
Qt 5.15.13
Operating System: Ubuntu 24.04.2 LTS
Desktop Env: Gnome 46
Windowing System: Wayland

In the past the clipboard wipe worked without installing wl-clipboard as described here: https://github.com/keepassxreboot/keepassxc/issues/11292#issuecomment-2369195332 However today I noticed that my clipboard isn't wiped after the countdown. I remembered this issue and installed wl-clipboard and that fixed the issue. So maybe wl-clipboard should be a dependency or at least a recommended package? You are the experts, I just thought you might be interested to know. @droidmonkey

**Comment by CowGivesMilk** [comment]
keepassxc 2.7.10-2
Distribution: Pacman
Desktop Env: KDE Plasma
Windowing System: Wayland
Clipboard manager: wl-clipboard (pacman)

Clipboard is not cleared when timer runs out, keepassxc is focused or not doesn't matter. 

https://youtu.be/V2EU9xH6ZpM

**Comment by cnd4** [comment]
Hello, I have the same issue (on Gnome Flatpak) but having wl-clipboard installed on host doesn't change anything (at least I have `wl-copy` and `wl-paste` but maybe it's more complicated than just having the binaries?).

**Comment by onur-tlntmr** [comment]
I reproduced fedora 42-43. I installed  dnf package manager.

keepassxc 2.7.10
Gnome shell 49.1 
Wayland 1.24.0-1

This issue may be related to Gnome.

**Comment by artlog** [comment]
> This isn't our bug. It's a bug/feature of GNOME on Wayland. We try to work around it by calling wlcopy directly instead of through Qt. Unfortunately we can't do that with Flatpak.

It look like using wl-copy now extends the requirement of having wl-clipboard installed to clear password  even if  keepassxc is focused or not. ( like @CowGivesMilk wrote ).

**Comment by spacebug42** [comment]
This is not only on the Flatpak version. The same issue is there in Debian native version.
(unless you install the wl-clipboard package)

Debian 13. (GNOME / Wayland session).
Keepassxc version: 2.7.10+dfsg1-1

**Comment by jpyllman** [comment]
Just a question, could this be a XWayland thing?? What I mean with that is the sync in between X11 and wayland might be broken.

This might make it mandatory to do these operations from wayland and not from X11. So then the application need to know if it is running as X11 under wayland. Will make ENV variable mess to support both environments at the same time?

**Comment by droidmonkey** [comment]
That would be Qt's problem not ours.

**Comment by droidmonkey** [comment]
> This is not only on the Flatpak version. The same issue is there in Debian native version.
> (unless you install the wl-clipboard package)

Well yeah you need to install it
