### ISSUE TITLE
--pw-stdin doesn't work on Windows

### ISSUE THREAD

**Issue by TheChiefMeat** [keepassxreboot/keepassxc#1185]
## Expected Behavior
Database is launched and unlocked, given the provided password and/or keyfile.

## Current Behavior
Database fails to unlock, only successfully reading the keyfile path (however databases with only a keyfile and without a password unlock successfully).

![keepassxc_2017-11-15_11-18-04](https://user-images.githubusercontent.com/17432768/32833742-d3867ef4-c9f7-11e7-8c23-89d3c0be4b9c.png)

## Steps to Reproduce (for bugs)

1. Run CMD with the below line (I'm unsure if each or any of these lines are correct, as the --help page doesn't specify).
2. keepassxc --keyfile ~/folder/keyfile.key --pw-stdin ~/anotherFolder/database.kdbx
3. keepassxc --keyfile ~/folder/keyfile.key --pw-stdin PASSWORD ~/anotherFolder/database.kdbx
4. keepassxc --keyfile ~/folder/keyfile.key --pw-stdin ~/anotherFolder/database.kdbx PASSWORD

## Context
I'm trying to launch my database without any user intervention at startup, and this issue is stopping me from doing so.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
I tried to get --pw-stdin to work on Windows and it just wasn't happening. The issue is mainly in how windows hands of gui apps from the cmd prompt. It is entirely different than Linux. I believe you can accomplish this using the "start" command though, ymmv.

**Comment by TheChiefMeat** [comment]
I've tried using the START command, but I'm entirely unsure how I'd get it to send the password from the CLI to KeePassXC, I know on the original KeePass is was -pw instead of the --pw-stdin we're using here.

One thing I've noticed is that regardless of what you type for the --keyfile parameter, even if the path doesn't exist, the parameter will still be send to KeePassXC.

![cmd_2017-11-15_12-39-23](https://user-images.githubusercontent.com/17432768/32836537-0c740d08-ca02-11e7-9c4c-07fd27ce6a74.png)

![keepassxc_2017-11-15_12-39-33](https://user-images.githubusercontent.com/17432768/32836549-14e018ce-ca02-11e7-99dc-8c86139c88c4.png)

Perhaps (I'm no expert) if a new parameter were to be made, say a clone of --keyfile, but instead this parameter would put it's information into the password box for KeePassXC, this issue could be fixed for WIndows? I assume that this parameter would be a Windows exclusive parameter seeing as it is working fine for Linux.

**Comment by droidmonkey** [comment]
Basically if you do that, anything running under your user account can get your password by harvesting the start-up script

**Comment by TheChiefMeat** [comment]
Can you point me in the right direction, what source files I should look at that control the CLI parameters? I'm super rusty on my coding, but I'll have a look if it means I might be able to help fix this issue, honestly it's the only thing stopping me from switching over to KeePassXC.

**Comment by droidmonkey** [comment]
Its mid way through main.cpp

**Comment by Remonli** [comment]
@TheChiefMeat  Looking forward good news for this to be fixed.

**Comment by TheChiefMeat** [comment]
I haven't actually been able to work on this at all yet. 

Can anyone help me get past this error? I've set up the env but every time I try to compile I get:

CMake Error at C:/msys64/mingw64/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibGPGError (missing: GPGERROR_LIBRARIES)
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibGPGError.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:234 (find_package)

**Comment by droidmonkey** [comment]
You need to install libgcrypt20-dev

**Comment by TheChiefMeat** [comment]
Honestly having trouble finding it, couldn't see it at all on the FTP server that gnupg has:

ftp://ftp.gnupg.org/gcrypt/

And msys2 comes up with:

$ pacman -S libgcrypt20-dev
error: target not found: libgcrypt20-dev

**Comment by droidmonkey** [comment]
Sorry my mistake, i was thinking Ubuntu. Here is the msys instructions per our wiki:

```pacman -S mingw-w64-$(uname -m)-qt5 \ mingw-w64-$(uname -m)-libgcrypt mingw-w64-$(uname -m)-zlib```

**Comment by TheChiefMeat** [comment]
Thanks, but I'm still getting the `error: target not found:  mingw-w64-x86_64-libgcrypt`

Managed to find it on the [https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/](url) page though and manually installed it.

**Comment by droidmonkey** [comment]
You might have to do a sync by performing ```pacman -Syu``` before attempting to install new packages. Either that or your msys install is a little janky because I see that package when I issue ```pacman -Ss libgcrypt```

**Comment by TheChiefMeat** [comment]
Welp, that was relatively easy, I fixed the --pw-stdin bug already xD

How do I merge the code to the main branch? I've never used Github before this.

**Comment by droidmonkey** [comment]
You'll want to first checkout develop, then make a new branch called ```hotfix/pw-stdin```, then commit your changes to that branch, then push it to your fork of keepassxc, then in your fork click on the "Create a PR" and follow the process.

**Comment by TheChiefMeat** [comment]
Forgot to say, opened up a pull request with the above fix.

**Comment by TheZ3ro** [comment]
I can't reproduce this
You have to start the database with:

`echo 'password' | keepassxc --keyfile ~/folder/keyfile.key --pw-stdin ~/anotherFolder/database.kdbx`

**Comment by phoerious** [comment]
On Windows? With cmd.exe or Powershell?

**Comment by TheZ3ro** [comment]
I'm using msys. I will test with cmd.exe and Powershell, alternatively I think I have a fix for other shells too

**Comment by TheZ3ro** [comment]
Nothing, I was trying
```
#ifdef _WIN32
if (AttachConsole(ATTACH_PARENT_PROCESS)) {
    freopen("CONIN$", "r", stdin);
    freopen("CONOUT$", "w", stdout);
    freopen("CONOUT$", "w", stderr);
}
#endif
```

But this doesn't seems to work. 
Powershell doesn't even start develop keepassxc.exe :'(

**Comment by phoerious** [comment]
Msys2 works differently, since it's basically a Unix shell.

**Comment by hifi** [comment]
I think I narrowed this down. If you try this:

```
echo foo | KeePassXC.exe --pw-stdin ...
```

the result will depend on your shell. In PowerShell the `echo` command works as expected but with the old `cmd.exe` it will include a whitespace at the end.

To use the `echo` command with old `cmd.exe`, you need to avoid having space before the pipe:

```
echo foo| KeePassXC.exe --pw-stdin ...
```

Redirecting a file works fine with both:

```
KeePassXC.exe --pw-stdin ... < password.txt
```

where `password.txt` contains your password in plain text.

I would expect any program that can output text on stdout will work just fine even on Windows to pipe it in.

**Comment by TheChiefMeat** [comment]
Can confirm that the following works with CMD even without the echo foo| before.

`KeePassxc.exe --pw-stdin < D:\KeePass\pw.txt D:\KeePass\NewDatabase.kdbx --keyfile G:\NewDatabase.key`

**Comment by hifi** [comment]
If you want to have your password on the command line itself you can use echo like so:

```
echo YOURPASSWORDHERE| KeePassXC.exe --pw-stdin D:\KeePass\NewDatabase.kdbx --keyfile G:\NewDatabase.key
```

But please bear in mind special characters will most likely break the echo command and as said before it's not a secure way to handle your passphrase.

**Comment by AustinHaigh** [comment]
Should this issue be closed? Looks like it was fixed: https://github.com/keepassxreboot/keepassxc/pull/1336#issuecomment-372121455

**Comment by droidmonkey** [comment]
Yup i agree

**Comment by TheChiefMeat** [comment]
I still can't seem to actually run the command. I've tried the three variants that I layed out before all those months ago, yet they still don't seem to work.

keepassxc --pw-stdin PASSWORD D:\KeePass\Database.kdbx

The password still doesn't get sent to the application and it's left hanging waiting for input.

**Comment by droidmonkey** [comment]
Yah I didn't understand what was going on in your PR, but looks like it was never merged.

**Comment by TheChiefMeat** [comment]
@droidmonkey It's okay, I guess there was just some confusion. The fix I did was a simple if statement, if someone wants to still implement that then the code can be found at the follow link (unfortunately that pull request was deleted ages ago under the assumption that it wouldn't ever be merged):

https://github.com/keepassxreboot/keepassxc/pull/1336/files

**Comment by Remonli** [comment]
Hope this get fixed soon.

**Comment by Remonli** [comment]
@droidmonkey  Hello , is this fixed on 2.4.0 ?  
I tried `keepassxc --pw-stdin PASSWORD D:\KeePass\Database.kdbx` but faild again.

**Comment by droidmonkey** [comment]
This *should* be fixed, Phoerious made improvements to handling the different stdin encodings on Windows. Are you using cmd shell or powershell?

**Comment by Remonli** [comment]
CMD , I tried different way, both failed , is there any mistake on the commands? 

KeePassXC.exe --pw-stdin PASSWD D:\keepass\database.kdbx
KeePassXC.exe  D:\keepass\database.kdbx --pw-stdin PASSWD

**Comment by helloworld52413** [comment]
@droidmonkey Doesn't seem to be fixed. I'm on 2.4.0 and running into the same issue with both `echo test | KeePassXC.exe --pw-stdin Passwords.kdbx` and `KeePassXC.exe --pw-stdin Passwords.kdbx < master.txt`. It opens the database, but it doesn't unlock it and it doesn't populate the password field either.

A database with just a key file (no password) can be opened just fine. However, when I try to combine a keyfile and a password like so `echo test | KeePassXC.exe --keyfile file --pw-stdin Passwords.kdbx` it doesn't even open the database -- just shows the welcome screen (with the "remember last used database"-option being disabled).

I used the traditional windows cmd on Win 10 (Build 1809).

**Comment by droidmonkey** [comment]
I'll give this a go in the debugger

**Comment by heX16** [comment]
Version 2.4.1 - still not working   :-(

**Comment by droidmonkey** [comment]
I tested this with 2.4.1 which also fixed opening databases from the command line. It works perfectly. If you are using the "echo" method, make sure you do not place a space between your password and the |. I'm going to close this issue.

**Comment by heX16** [comment]
```
set /p pass=<h:\KEY\k
echo %pass%
echo %pass%|start "" KeePassXC.exe --pw-stdin D:\NetDrive\Data\keep\hex
pause
```

![image](https://user-images.githubusercontent.com/3930496/56502602-916ef080-651b-11e9-86e2-9652a911eccc.png)

**Comment by phoerious** [comment]
I don't think this feature is working in Windows or did we find a way to make it work? In any case, it shouldn't crash.

**Comment by droidmonkey** [comment]
Interesting, this does not work from the batch file I created replicating your setup. It also does not work in mingw. It appears to be broken again!

**Comment by BARR001** [comment]
Hello, i also have the same problem. Tried everything, but nothing works. Cant't send my password. would this be fixed in future?

**Comment by heX16** [comment]
> 
> 
> Hello, i also have the same problem. Tried everything, but nothing works. Cant't send my password. would this be fixed in future?

I just create file with password and use "--keyfile".

Example:
    start "" KeePassXC.exe --config "%~d0%~p0\keepassxc.ini" --keyfile D:\xxx\mypasswd D:\xxx\database

**Comment by BARR001** [comment]
Hello, i know that this works. But i have to use a passwort because everyone who uses my PC can open the database. My batchfile has an input parameter like (set /p Input=Enter Crypt:) so the password isn't stored in this file!

**Comment by droidmonkey** [comment]
What's the point? Why can't you just enter the password after KeePassXC opens

**Comment by BARR001** [comment]
im starting different programs in a batch. Most have the same Password, so i have to fill it only once!

**Comment by heX16** [comment]
@BARR001 , Yes, I also wanted to do this: for another program to take the password from a physical device ([digispark](http://digistump.com/products/1) with homemade firmware (as [Memtype](https://hackaday.io/project/8342-memtype-open-source-password-keeper)) ).
But for the last 2 years I just keep the file in a shared cryptographic repository... And waiting until "pw-stdin" is implemented. :smile:

**Comment by BARR001** [comment]
I'm sorry, but I changed now to the original KeePass and the paramenter -pw: works fine for me. It is realy pity.

**Comment by ChiaYen-Kan** [comment]
Did keepassxc is build with "-Wl,-subsystem,windows" in win32 ?
In win32 system if build with "-Wl,-subsystem,windows" will don't have stdin/stdout in default
so, with --pw-stdin will can't  read and write from console
but if build without "-Wl,-subsystem,windows", the program will be have gui and console in same time, when close console, gui is also be closed
may be can add new "-pw:" parameter  just like KeePass

**Comment by BARR001** [comment]
i found a solution that works for me
echo password| "C:\Program Files\KeePassXC\KeePassXC.exe" --pw-stdin "D:\test.kdbx" --keyfile "D:\Bild.jpg"

**Comment by BitWuehler** [comment]
@BARR001 I tried that and i doesn't worked. But if use the portable version everything works fine. How do you managed, that the batch file closes after it opened the programm? My only closes from itself, if I close the programm.

**Comment by droidmonkey** [comment]
You must not include a space between the password and the pipe |

**Comment by BARR001** [comment]
> 
> 
> @BARR001 I tried that and i doesn't worked. But if use the portable version everything works fine. How do you managed, that the batch file closes after it opened the programm? My only closes from itself, if I close the programm.

i don't have a solution yet. The console keeps open

**Comment by BARR001** [comment]
> 
> 
> You must not include a space between the password and the pipe |

there is no space. It works fine.  It also works if there is no space before and after the pile, like
echo test123|"D:\LupoPenSuite\KeePassXC.exe" --pw-stdin "D:\test.kdbx"

**Comment by BitWuehler** [comment]
Thanks @BARR001 
I found something interesting. Seems like it is a problem with the Browser integration. Thats also the reason why it worked for me before with the portable version. I don't configurate it before. But if I now activate the browser integration the hole password fill thing doesn't work anymore.

**Comment by BARR001** [comment]
But i have a new Problem so this solution is not useful for me!
If i activate Browser Integration the Software crashes, because only the last three characters from the password where forwardet.
for this i made a new bug report
https://github.com/keepassxreboot/keepassxc/issues/4140

**Comment by higuti-yuuma** [comment]
> > @BARR001 I tried that and i doesn't worked. But if use the portable version everything works fine. How do you managed, that the batch file closes after it opened the programm? My only closes from itself, if I close the programm.
> 
> i don't have a solution yet. The console keeps open

You can close the console by running it through a power shell from a batch file.

```bat
@echo off
setlocal
cd /d %~dp0

set kdbx=your.kdbx
set pass=password.txt
set key=keyfile.key

set script=Start-Process -FilePath "KeePassXC.exe" -ArgumentList "%kdbx% --keyfile %key% --pw-stdin" -RedirectStandardInput "%pass%"
set script=%script:"=\"%
powershell -Command "%script%"

endlocal
```

**Comment by m-a-v** [comment]
> ```
> echo YOURPASSWORDHERE| KeePassXC.exe --pw-stdin D:\KeePass\NewDatabase.kdbx --keyfile G:\NewDatabase.key
> ```

`echo` adds a newline by default. Use the following comnmand to avoid this.

```
<NUL set /p="YOURPASSWORDHERE" | KeePassXC.exe --pw-stdin D:\KeePass\NewDatabase.kdbx --keyfile G:\NewDatabase.key
```

**Comment by steel4me** [comment]
> > > @BARR001 I tried that and i doesn't worked. But if use the portable version everything works fine. How do you managed, that the batch file closes after it opened the programm? My only closes from itself, if I close the programm.
> > 
> > 
> > i don't have a solution yet. The console keeps open
> 
> You can close the console by running it through a power shell from a batch file.
> 
> ```batchfile
> @echo off
> setlocal
> cd /d %~dp0
> 
> set kdbx=your.kdbx
> set pass=password.txt
> set key=keyfile.key
> 
> set script=Start-Process -FilePath "KeePassXC.exe" -ArgumentList "%kdbx% --keyfile %key% --pw-stdin" -RedirectStandardInput "%pass%"
> set script=%script:"=\"%
> powershell -Command "%script%"
> 
> endlocal
> ```

very useful, someone have a batch or powershell to open multiple databases? i tried it months ago and i cant open second or third database with stdin

**Comment by m-a-v** [comment]
> very useful, someone have a batch or powershell to open multiple databases? 

It's easier to use the AutoOpen feature as described here:

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening

**Comment by steel4me** [comment]
> > very useful, someone have a batch or powershell to open multiple databases?
> 
> @steel4me It's easier to use the AutoOpen feature as described here:
> 
> https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening

I love you! Thx!

Was AutoOpen always there or has been introduced in the last updates?

**Comment by m-a-v** [comment]
https://github.com/keepassxreboot/keepassxc/issues/477

**Comment by steel4me** [comment]
> #477

facepalm, strange that i didn't found it myself, sorry

**Comment by steel4me** [comment]
@m-a-v 
AutoOpen is very cool! I already open local databases without problems. 
But when i try to open databases from cifs / smb share, 
how can i add username and password for this share. Example:

kdbx://file://192.192.192.192/share
i tried kdbx://files://domain\user.name:password@192.192.192.192

**Comment by BARR001** [comment]
hello community
does anyone know when --pw-stdin will be implemented? I#m using version 2.6.6.
My actual problem is that my batch stops when i start KeePassXc with following command
echo password| "C:\Program Files\KeePassXC\KeePassXC.exe" --pw-stdin "D:\test.kdbx" --keyfile "D:\Bild.jpg"

after starting i want to start firefox that need the proxy of KeePassXC

**Comment by m-a-v** [comment]
You could use an AutoIt script ...

```
#include <AutoItConstants.au3>

$executable = "C:\Program Files\KeePassXC\KeePassXC.exe"
$kdbx = "C:\Users\Dummy\Dummy.kdbx"
$pass = "i_am_aware_that_this_is_a_really_insecure_method_to_provide_the_pw_using_stdin"
$cmd = $executable & " " & $kdbx & " --pw-stdin"
Local $iPID = Run($cmd, @SystemDir, @SW_HIDE, $STDIN_CHILD + $STDOUT_CHILD)
StdinWrite($iPID, $pass)

If WinExists ("Dummy- KeePassXC") Then
	WinSetState ("Dummy- KeePassXC", "", @SW_HIDE)
EndIf

Exit (0)
```

**Comment by droidmonkey** [comment]
This feature works on Windows, you just have to use it "carefully"

**Comment by beyond9thousand** [comment]
You guys could include straightforward instructions to use this feature on Windows, you know? How do i pass a password with special characters? In my case it doesn't pass % and the character following it

**Comment by BARR001** [comment]
try %% or \% or /%

**Comment by jvachez-max** [comment]
Seems there's a problem with french accents like é ô
