### ISSUE TITLE
MacOS: Auto-Type when database locked causes main window to steal focus

### ISSUE THREAD

**Issue by klara31** [keepassxreboot/keepassxc#1216]
I am using KeepassXC on MacOS. When I press the hotkey to autotype a password in Safari, two instances of KeepassXC are opening to enter the database password. 
![schermafbeelding 2017-11-23 om 08 52 10](https://user-images.githubusercontent.com/1309136/33162915-41d3c512-d02c-11e7-92f6-62b736b3469d.png)

If I enter the password in one of the instances (in this case: the one on top), the following error is displayed:
![schermafbeelding 2017-11-23 om 08 55 30](https://user-images.githubusercontent.com/1309136/33162888-2432da66-d02c-11e7-8ed6-ce6ecc15eedf.png)
(translated: could not find an element with window title: About KeepassXC)

## Expected Behavior
Only one instance should open.

## Current Behavior
Two instances open

## Steps to Reproduce (for bugs)
Press hotkey combination to autotype username and password in Safari

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.2.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by RicardoCapricciosa** [comment]
I can confirm this issue, but it occurs only if the database is locked.

**Comment by hfr-hfr** [comment]
This is still an issue with v2.3.0

**Comment by anshulbajpai** [comment]
Yes, this issue still exist

**Comment by anshulbajpai** [comment]
I'd like to add more to this bug. 
When we press the global hotkey to summon auto-type (with the browser in foreground) on a closed database and after entering the password, we see a modal dialog saying "Couldn't find the entry that matches the window title: **** - KeePassXC". 
When we press the OK button, then the KeePassXC application is in the foreground, whereas the expected behaviour would be to bring the browser again in the foreground.

**Comment by emilbayes** [comment]
The problem with focus seems solve for me in 2.3.1, but it still cannot find the correct password if the database was previously locked

**Comment by hfr-hfr** [comment]
Yes, the issue still exists in 2.3.1:

> Focus is now set correctly on password field. But the other issue (using wrong window title for autotype) remains. Here's my summary of this bug from October last year:

>> after unlocking the database (…) KeepassXC should use the prior window (where global Auto-Type keyboard shortcut was invoked) to check against auto-type rules. Instead it uses its own window ("database-name KeepassXC") and consequently presents an error dialog "no entry found with that window title".

**Comment by klara31** [comment]
Problem still exists in 2.3.3

**Comment by RicardoCapricciosa** [comment]
Problem still exists in 2.3.4

Is there anything we can do to support development (as a non developer?) As this is one of the most annoying bugs I have to deal with a hundred time every day.

**Comment by droidmonkey** [comment]
This is fixed in 2.4.0. Please test the beta version available under releases.

**Comment by droidmonkey** [comment]
See #1904 for the fix implementation

**Comment by klara31** [comment]
I just tried this with 2.4.0-beta2, problem still exists in this version

**Comment by RicardoCapricciosa** [comment]
I can confirm the observation of @klara31. The problem is still there with v2.4.0-beta2 (tested on MacOS X 10.14.3)

**Comment by veysiertekin** [comment]
Hi,
I can confirm that problem still exists in KeePassXC 2.4.1 on macOS 10.14.3.

**Comment by droidmonkey** [comment]
I have made a fix for this, see PR link above.
