### ISSUE TITLE
Ctrl + C triggers copy of password while text from notes preview panel is selected

### ISSUE THREAD

**Issue by Conan1989** [keepassxreboot/keepassxc#1653]
## Expected Behavior
Select text form notes preview panel, press Ctrl + C, selected text copied to clipboard

## Current Behavior
password from the associated entry is copied to clipboard

please find the attached video
https://giant.gfycat.com/LimpBlaringDeviltasmanian.webm

same behavior observed in both Linux and Windows version

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. create an password entry with notes 
2. use the preview panel to select text from the notes
3. press Ctrl C
4. paste somehwere

## Context
N/A

## Debug Info
# Arch Linux

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

#########

# Windows

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TjarkoG** [comment]
Isn't this by design?
The "Entries" tab Explicitly shows "Ctrl + C" as shortcut for "Copy password"

**Comment by pquerner** [comment]
Can confirm in 

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by chrsmrtnx** [comment]
Still present in 2.3.4 on Linux (running KDE). Would be great to have this fixed in the next release.

---

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.17.0-3-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This was fixed in #2431

**Comment by Roukaysa** [comment]
I still have this issue.

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by tf42src** [comment]
v2.7.9 is still not copying highlighted text, but passwords.
