### ISSUE TITLE
KeePassXC 2.3.1 - Doesn't remember window size

### ISSUE THREAD

**Issue by chrsmrtnx** [keepassxreboot/keepassxc#1756]
## Expected Behavior
KeePassXC 2.3.1 should remember its window size even when the app is "closed" and "hide window to system tray instead of app exit" is selected, and also when "minimize when copying to clipboard" is being used.

## Current Behavior
I have found two ways to trigger the problem:

Firstly - If I (say) maximize KeePassXC, then "close" the app, instead of using the minimize button, the app disappears into the system tray as expected, because I have "hide window to system tray instead of app exit" set. But then when I restore KeePassXC, it is no longer maximized, but has reverted to some other default window size.

If, instead, I maximize KeePassXC, then minimize it (instead of "closing" it), then KeePassXC retains its window size when restored as expected and desired.

Since, with "hide window to system tray instead of app exit", minimize and close are effectively identical, I would expect them to behave identically with respect to remembering window sizing.

Secondly - If I (say) maximize KeePassXC, then copy a username or password to the clipboard while "minimize when copying to clipboard" is set, KeePassXC disappears as expected. But when I restore it, it has lost its maximized status and has reverted to some other window size.

## Context
This is a small bug, but it's very irritating, because instead of smoothly flipping back and forth between KeePassXC and other apps, I constantly have to re-maximize KeePassXC because the entry I was dealing with was hidden when the window shrank.

The original keepassx 0.4.x worked fine in this regard, so this is a regression in a broad sense.

## Debug Info
Desktop environment: KDE 5.12

KeePassXC 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.15.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
State persistence should be fixed and I cannot reproduce this issue.

**Comment by monkeydri** [comment]
Well I am still experiencing this.

Every time I open the app it opens in the same state (windows roughly takes half of the screen).

1. open app => state 1 : window half screen
2. maximize window
3. close app (real close)
4. open app => back to state 1

KeepassXC 2.3.1 from ppa on Ubuntu 18.04
