### ISSUE TITLE
Main window pops up after browser selection dialog

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#2579]
Since »Switch browser integration to use native raising of windows« (5488f1bfc336219bed677e67a63954c3959ecace) the main window pops up after the dialogue for selecting the credentials.

1. Start KeePassXC and unlock the database
1. Put KeePassXC into tray-icon mode (hide the window)
1. Go to a website that asks for a password.
1. After closing the dialogue the main window pops up.

**Comment by varjolintu** [comment]
Fixed it. You can give the PR a try if you like to test it.

**Comment by jo-so** [comment]
I'm sorry, but PR #2583 doesn't fix my problem. After applying the patch of the PR the main window still pops up after the dialogue.

**Comment by varjolintu** [comment]
Just for confirmation, do you hide the window using Cmd+H or is it minimized to the dock? Can you do a screen recording of this? I cannot reproduce it.

**Comment by jo-so** [comment]
Sami Vänttinen hat am So 06. Jan, 06:15 (-0800) geschrieben:
> Just for confirmation, do you hide the window using Cmd+H or is it minimized to the dock? Can you do a screen recording of this? I cannot reproduce it.

Yes, I use Ctrl+m to put the window to the tray bar. It's no longer
visible in the task bar.

-- 
chinesiches Sprichwort:
Wer fragt, ist ein Narr für fünf Minuten.
Wer nicht fragt, ist ein Narr fürs ganze Leben.

**Comment by varjolintu** [comment]
I still cannot reproduce it. The only time the main window will pop up is if the application is activated or the browser window is hidden. This triggers the previous window to activate (macOS behaviour).

**Comment by varjolintu** [comment]
So this is happens in a Linux enviroment? What is your window manager? I thought we were talking about macOS. You removed the issue template, so please write it again.

**Comment by jo-so** [comment]
Sami Vänttinen hat am Mi 09. Jan, 02:10 (-0800) geschrieben:
> So this is happens in a Linux enviroment? What is your window manager? I
> thought we were talking about macOS. You removed the issue template, so
> please write it again.

Sorry, I didn't mention this. Yes, I'm using Linux and my window manager
is AwesomeWM.

-- 
Je planmäßiger ein Mensch vorgeht,
desto stärker mag ihn der Zufall treffen.
                    Erich Krunau ‚Die Physiker‘

**Comment by jo-so** [comment]
I've tried the develop branch b59fd6d06ad and the bug described in this issue isn't fixed.

**Comment by varjolintu** [comment]
This has something to do with AwesomeWM. I tried the same case with i3 and Cinnamon and I couldn't reproduce the problem. I'm pretty certain AwesomeWM is not actually hiding the window but doing something else.

**Comment by jo-so** [comment]
I've debugged into this problem. The raise of the window gets triggered by `getMainWindow()->showMinimized()` in `BrowserService::hideWindow()`.

```
(gdb) bt 4
#0  BrowserService::hideWindow (this=0x563b36dc79d0) at /home/joerg/git/keepassxc/src/browser/BrowserService.cpp:1012
#1  0x0000563b36831a58 in BrowserService::confirmEntries (this=0x563b36dc79d0, pwEntriesToConfirm=..., url=..., host=..., submitHost=..., realm=...) at /home/joerg/git/keepassxc/src/browser/BrowserService.cpp:717
#2  0x0000563b3682eff3 in BrowserService::findMatchingEntries (this=0x563b36dc79d0, id=..., url=..., submitUrl=..., realm=..., keyList=..., httpAuth=false) at /home/joerg/git/keepassxc/src/browser/BrowserService.cpp:324
#3  0x0000563b36846558 in BrowserAction::handleGetLogins (this=0x7f72a0007a10, json=..., action=...) at /home/joerg/git/keepassxc/src/browser/BrowserAction.cpp:260
(More stack frames follow...)
(gdb) p m_wasMinimized
$6 = true
```

The patch changed
```diff
@@ -920,7 +964,7 @@ void BrowserService::databaseUnlocked(DatabaseWidget* dbWidget)
 {
     if (dbWidget) {
         if (m_bringToFrontRequested) {
-            getMainWindow()->lower();
+            hideWindow();
             m_bringToFrontRequested = false;
         }
         emit databaseUnlocked();
```

Due to `m_wasMinimized` is *true* in this case, the patch effectively replace `getMainWindow()->lower()` by `getMainWindow()->showMinimized()`.

**Comment by varjolintu** [comment]
@jo-so There are some changes in the `release/2.4.0` branch. We need to make a new fix there if this bug is still valid.

**Comment by jo-so** [comment]
Is 2.4.0 part of devel? The bug is still present in 8bfc53923445a7a.

**Comment by varjolintu** [comment]
@jo-so The fix is in `release/2.4.0` branch. Please see https://github.com/keepassxreboot/keepassxc/pull/2667.

**Comment by jo-so** [comment]
I've pulled the PR 2667 on top of devel and this fixes this bug.

**Comment by droidmonkey** [comment]
Sweet. You could also just checkout the release/2.4.0 branch
