### ISSUE TITLE
Advanced Search Issues "Search Help" won't stay visible, cannot do advanced search

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#2814]
## Expected Behavior
I expected to be able to do an advanced search.

## Current Behavior
Clicking on the green help icon for search help causes a popup display that immediately disappears, so it isn't useful.

## Steps to Reproduce
1. Open database and unlock database with v2.4.0 version
2. Click on "Help icon" that has a tool tip of "Search Help"

The actual "Help" menu has nothing about "Help" at all either.

## Context
Can't use advanced help, which I was looking forward to.  Non-advanced help still works as before.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: Devuan GNU/Linux ascii
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64 [SMP Debian 4.9.88-1+deb9u1 (2018-05-07)]

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by kneitinger** [comment]
I am also experiencing this on i3 with KeePassXC always in floating mode.

@affinityv can you please share what desktop environment/window manager you are using?

**Comment by droidmonkey** [comment]
The help popup needs to be completely redone, I did not have time to do it for 2.4.0. Expect this in future releases.

**Comment by affinityv** [comment]
> I am also experiencing this on i3 with KeePassXC always in floating mode.
> 
> @affinityv can you please share what desktop environment/window manager you are using?

xfce

**Comment by courtarro** [comment]
I'm also using xfce (Xubuntu 18.04), so perhaps it's an incompatibility with that environment.

**Comment by tomhundt** [comment]
Maybe this is fixed?  It does stay up in mine (3.4.3 on Mac).  My problem is it's hard to get rid of it -- it can only be done by clicking the question-mark-in-circle icon again.  Not by hitting Esc, nor by clicking outside the help box.

**Comment by affinityv** [comment]
Still the same with latest version.

KeePassXC - Version 2.5.2
Revision: 62cda9d
Distribution: AppImage

Qt 5.12.6
Debugging mode is disabled.

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.19.0-5-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
We have formal documentation now, Help -> User Guide

**Comment by gwisp2** [comment]
I have the same issue with ArchLinux + Mate + Qt 5.14.
I did some investigation and found out why it happens:
1. Showing help popup leads to main window becoming inactive
2. Search box loses focus when main window becomes inactive
3. Help popup hides when search box loses focus

Also it causes TestGui::testSearch to fail sometimes due to failed focus assertions on different lines because window becomes inactive at a random time.

**Comment by droidmonkey** [comment]
Nice find!
