### ISSUE TITLE
Ubuntu 18.04: the database does not lock when the session is locked

### ISSUE THREAD

**Issue by nbinns** [keepassxreboot/keepassxc#3027]
On Ubuntu Linux 18.04, the database does not lock when the session is locked by pressing the Windows/Super key + L

## Expected Behavior
The database should be locked when the session is locked. This works as expected on Windows 10, but not on Ubuntu Linux 18.04

## Current Behavior
The database does not lock when the session is locked by pressing the Windows/Super key + L.

## Possible Solution
Note: pressing Ctrl + L does lock the database. This can be used as a workaround before locking the session, but relies on the user remembering to do this

## Steps to Reproduce

1. Open database
2. Press Windows/Super + L
3. Database remains unlocked

## Context
When I lock my session, my password database remains unlocked and therefore insecure

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This is most likely related to being in the snap. Snapd was recently updated and broke a lot of integrations with the desktop environment. I wouldn't be surprised if picking up on session lock was also broken as a result.

**Comment by joshirio** [comment]
The snapcraft.yaml is missing the `desktop` plug which allows to query the screen lock status, see https://github.com/snapcore/snapd/pull/4385

So just adding `desktop` to the plugs list should fix this. In fact, I just tested it and it works.
https://docs.snapcraft.io/the-desktop-interfaces/2042

**Comment by phil-opp** [comment]
I still see this issue with version 2.4.2. I have the option _"Lock databases when session is locked or lid is closed"_ enabled, but the database remains unlocked after resuming a locked session.

Like @nbinns , I'm using the snap package. I used the PPA package before, where it worked without problems.

<details>
<summary>Debug Info</summary>


> KeePassXC - Version 2.4.2
> Revision: b5bc1aa
> Distribution: Snap
> 
> Qt 5.9.5
> Debugging mode is disabled.
> 
> Operating system: Ubuntu Core 18
> CPU architecture: x86_64
> Kernel: linux 4.15.0-50-generic
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> 
> Cryptographic libraries:
> libgcrypt 1.8.1


</details>

**Comment by joshirio** [comment]
For me it is working on 2.4.2 on Ubuntu 18.04, installed also via `snap`. What distro/DE are you using?

**Comment by phil-opp** [comment]
I'm on Ubuntu MATE 18.04.2, using snap 2.39.
