### ISSUE TITLE
Auto-Type Problems with @ in username

### ISSUE THREAD

**Issue by rgloor** [keepassxreboot/keepassxc#324]
## Expected Behavior

When using Auto-Type, correct USERNAME should be inserted in Form:
eg:  myname@mydomain.tld

## Current Behavior

Auto-Type replaces the  @  by a  "  , so it would enter a wrong USERNAME into the Form:
eg: myname"mydomain.tld     instead of   myname@mydomain.tld

## Possible Solution

?

## Steps to Reproduce (for bugs)

1. Go to "site" or app or what-so-ever
2. Put cursor into the first formfield (eg. for username)
3. Press Auto-Type Global HotKey
4. Select the entry

## Context

Trying to insert credentials for login  into accounts on websites.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) : 
  KeePassXC v2.1.0
* Qt version (e.g. Qt 5.3): 
   Qt 5.6.1
* Compiler (e.g. Clang++3.6.0): 
  N/A
* Operating System and version: 
  openSUSE LEAP 42.2 (fully patched)

## Note
It might be not KeePassXC itself, because it could be, that the behavior changed after the last upgrade of KeePassXC. But I am not absolutely sure.
However, you might still be able to track down the source of the problem and help fixing it.

**Comment by rgloor** [comment]
**partially "solved"**
I don't know what happened. All by a sudden, it worked again!
To test, I had opened the Text-Editor KWrite, wrote a KeePassXC-DUMMY-entry for KWrite. And within KWrite, I started Auto-Type and that way could test, what was handed over.
Before shutting down the Notebook, after closing down all apps, I had the KWrite left, and just did another Auto-Type Test.
And surprisingly, it was working again.

So the issue has disappeared for me now.
But I am sure, the source of the problem is not yet solved.

I will keep an eye on it and see, if I can get it to reproduce again.

**Comment by TheZ3ro** [comment]
From a code point of view, nothing changed in Autotype in the last version.
[This](https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Entry.cpp#L661) is the function that replace the `{USERNAME}` keyword and [this](https://github.com/keepassxreboot/keepassxc/blob/423de39ad0927ac90bbe43ca1781fdec8c24db25/src/autotype/AutoType.cpp#L526) loop inject the username's key in the text field.

 I can't reproduce this on my PC. I will leave the issue open with a "more info needed" tag, ok?

**Comment by rockihack** [comment]
This is a keyboard layout issue. Keepassxc and your system use different layouts.
`Shift + 2` produces a `@` character in US layout, but your system uses some other layout where `Shift + 2` produces a `"`.

**Comment by phoerious** [comment]
Yes, autotype is bound to your keyboard layout. Are you using the app image? We had an issue here where the AppImage always used a US layout on Fedora, although it should have used an AZERTY layout. I was never able to reproduce it.

**Comment by phoerious** [comment]
Closing since we can't reproduce and it seems to be working for you again.
Most likely not a KeePassXC issue anyway.

**Comment by TheZ3ro** [comment]
I've experienced this the other day when my system layout was IT and Autotype sadly is US-only like @rockihack said.
Reopening this.

There is a method to change the autotype layout? If not we can close again

**Comment by rockihack** [comment]
I never said that autotype is US-only. It seems to be a bug in xkb autotype or your display server.

https://github.com/keepassxreboot/keepassxc/blob/1f6f7b614ce3528f24958d2025289b96665119fe/src/autotype/xcb/AutoTypeXCB.cpp#L223

**Comment by phoerious** [comment]
Problem seems to be that autotype sometimes doesn't respect the user's keyboard layout and then falls back to a US layout. But I have no idea why.

**Comment by rgloor** [comment]
Still not fixed. Had problem again.
Yesterday, just installed KeePassXC v2.1.3.   and it worked again.
After restarting the system this morning. Problem is here again.
Closed KeePassXC, restarted it again. Now working again..... but not having any clue, what will trigger the misbehavior again.
So issue is still open.

**Comment by rgloor** [comment]
Tracked it down a bit:
When I shut down my system (openSUSE LEAP 42.2), I usually leave KeePassXC running.
So when I start it up again, KeePassXC comes up as well after login.
What I found:
- When KeePassXC is started automatically, the keyboard mapping / layout is wrong (@ -> ").
- When I close KeePassXC and restart it again, everything works fine (@ -> @).

So when KeePassXC is starting within the start up process / login process of the system, it might initiate before the correct keyboard layout is defined.

Is there a startup / login sequence where KeePassXC might wait for a certain event to be passed before it starts up or defines the keyboard? Just a thought.

**Comment by droidmonkey** [comment]
If you want to wait for events, use udev or similar. I would just add it to the end of your .bash_profile or equiv file.

**Comment by phoerious** [comment]
I really think, this is tied to the Qt bug I linked above. KeePassXC gets the correct layout when it is already set, but when it changes during runtime, KeePassXC doesn't notice.

**Comment by nivit** [comment]
@TheZ3ro I have the same issue with the italian layout. Solved with the following commands:

`xmodmap -e 'clear mod5'`
`xmodmap -e 'add mod5 = ISO_Level3_Shift'`

Maybe I know why keepassxc sends/auto-types "wrong" characters and why those commands solve this issue (at least for the italian layout)...

**Comment by frostasm** [comment]
I have similar problem with "Ukrainian" keyboard layout and I wrote a small fix. Before "auto-typing" procedure keepassxc change the system layout to "English" and after "auto-typing" return back the  original layout.

![image](https://user-images.githubusercontent.com/3104366/32441995-691307c8-c302-11e7-9877-1186babc0c88.png)

**Comment by droidmonkey** [comment]
That's great! It would be even better if the user could set a desired keyboard layout in settings. Default being "us".

**Comment by frostasm** [comment]
@droidmonkey I can prepare PR with related changes. But at the moment my fix is relevant only for Linux, what about the others operation systems?

**Comment by frostasm** [comment]
And one more note, method with changing system keyboard layout only works assuming that the "us" layout will be the first in the list of layouts, otherwise, changing the layout does not help :(

![image](https://user-images.githubusercontent.com/3104366/32507104-3c74e5b8-c3ef-11e7-8f1d-a1ea04dfba2d.png)

**Comment by droidmonkey** [comment]
This definitely requires more discussion and investigation, but i think we are on the right track. I have not heard any complaints about autotype on windows or mac with alternate keyboards. This might be a linux only change and can be ifdef'd as such.

**Comment by stratacast** [comment]
I can confirm this is not an issue on Windows 10, but is an issue with all my Linux boxes

**Comment by frostasm** [comment]
@keepassxreboot/core-developers can we use GPL code from other projects in KeePassXC?

I use **XKeyboard** class from [nonpop/xkblayout-state](https://github.com/nonpop/xkblayout-state) project. I used that class for changing system keyboard layout.

**Comment by droidmonkey** [comment]
As long as you keep the license header and add the origination information to the COPYING file.

**Comment by skontar** [comment]
As far as I can tell, the Autotype feature just types as if the active layout would be US. So if my password contains numbers like "234" it is going to type "ěšč" on CZ layout. One workaround I have is a script, which changes the layout before it sends the autotype key combination (however it does not change back).

```
    setxkbmap -model pc104 -layout us -option grp:caps_toggle
    xdotool keyup super
    xdotool key alt+ctrl+a
```
In the application you can probably store the current layout, switch to US, type, switch back.

**Comment by rgloor** [comment]
Just an Idea:
Very rarely, people change keyboards during the day. So,
- if KeePassXC would check system keyboard layout at the very first time it is used (for auto-type, because I think that is the only area it shows the issue), and then adjust if necessary

Alternatively, if it is not slowing the app down too much,
- KeePassXC could check system keyboard layout at every use of auto-type

Just my 2 cents.

**Comment by frostasm** [comment]
I made a temporary solution (change system layout at every auto-type action), but in my opinion it is a ugly hack. It is probably better to find another solution to the problem or use xdotool library.

@TheZ3ro  you can see my changes in [this commit](https://github.com/frostasm/keepassxc/commit/8b7331182eb1ef49558a30394df71f60bdd4b7a7)

**Comment by robinedser** [comment]
Came across this issue just recently when I got a Dell XPS 15 with the UK keyboard layout. It's possibly a very rare edge case but my set up is as follows:

- Hardware: Dell XPS 15 with UK Keyboard
- Host OS: Solus
- KeePassXC Version: Latest Snap
- VirtualBox Guest: Ubuntu 18.04

I get the behaviour described above where the @ sign in an email address is typed as a " but only when autotyped in a VM running in VirtualBox. Both the host (solus) and the guest (ubuntu) are set to UK keyboard layout, but when you autotype from KeePassXC into the VM it goes wrong.

Not a major issue in the end - copy and paste via clipboard works without problems just though it was an interesting quirk.

**Comment by rgloor** [comment]
@robinedser 
Did you have KeePassXC on "autostart"? 
Or did it happen when you manually started it after the OS was up?

**Comment by robinedser** [comment]
It's not on autostart, I open it manually after the OS is up. Then there are no issues autotyping into a terminal or browser on the host - just autotyping into a Virtualbox Guest window. Could even be a Virtualbox issue I guess.

**Comment by tuxether** [comment]
I can reproduce this problem with the AppImage on QubesOS, which is inside a VM because of how QubesOS works.

**Comment by mwip** [comment]
Still have the same problem. 
Working on a 
* Linux Mint 19 XFCE 
* Virtualbox virtual machine 
* with keepassxc 2.3.4
* and two layouts. 

As @rgloor guessed, I switch between two layouts throughout the day (EN_US and DE). Whenever I am working on the DE layout, the auto-type will insert " instead of @. This occurs for both autostarted as well as manually started keepassxc instances. 
On my private machine (Arch linux, KDE Plasma, keepassxc 2.3.4, two layouts [EN_US / DE]) I never stumbled over this behaviour.

**Comment by jtrh** [comment]
I experienced this problem today.

My system's characteristics are:

- **KeePassXC version**: 2.3.4
- **OS**: Xubuntu 18.04.1 LTS
- **Machine**: VirtualBox 6.0.0 (Windows 10 host)
- **Locale**: en_US
- **Desktop environment**: Xfce 4.12

I have multiple keyboard layouts configured in Xfce: _English (US)_ (set as default), and _Spanish_. When I change the _current_ keyboard layout to _Spanish_, every application respects it, except KeePassXC's auto-type, which insists on using _English (US)_.

The issue seems to be that KeePassXC always uses the _default_ keyboard layout, instead of the _current_ layout. If you have multiple layouts configured in Xfce, you can change the current layout by using a tool such as the [Keyboard Layouts panel plugin](https://goodies.xfce.org/projects/panel-plugins/xfce4-xkb-plugin).

I "fixed" the issue by changing the default keyboard layout to _Spanish_. However, if I try to change the current layout to _English (US)_, the problem returns, but with the languages reversed.

**Comment by achilleas-k** [comment]
I had this same issue on one machine and not another (with nearly identical software setups) and I found the setting which, in my case, solved the issue. Not sure if this information will help or make things more confusing.

I have two layouts: UK and Greek.

OS: ArchLinux
KeePassXC version: 2.3.4
Locale: en_GB.UTF-8
Desktop environment: KDE Plasma

In Plasma, the keyboard layout options have an option for policies: Global, Desktop, Application, Window. It was set to Window, meaning the layout is allowed to be different for different windows of the same application. Switching it to Application instead solved the issue for me. Even more interestingly, switching it back to Window doesn't recreate the issue.

I don't know what this means. It's possible whatever window context auto-type was working in was "stuck" (possibly from when I first set up the system or some time before setting up layouts) in a US layout and changing the policy made it inherit the application's layout (which is now UK).

Like I said, not sure if my experience helps, makes things more confusing, or if I'm just adding noise, but I thought it might be interesting.

**Comment by sxe** [comment]
At this point I am pretty convinced this is a problem related to the systems keyboard layout on Linux. It's not just that @ is printed as ". Today I noticed that also y is printed as z. I have a "German keyboard" and exactly this happens when you use an English keyboard layout cause y and z are switched. German has qwertz not qwerty.

Her is my layout after fully booted:
> $  setxkbmap -query | grep layout
> layout:     de

My system is set to this after fully booted and KPXC is running:
> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=de_DE.UTF-8
> LC_TIME=de_DE.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=

These two are en_US.UTF-8 at boot time as well but get changed to de_DE.UTF-8 from KDE after boot.
> LC_NUMERIC=de_DE.UTF-8
> LC_TIME=de_DE.UTF-8

Not sure how relevant the locale is, I just wanted to add it.

Hope this helps. 

Cheers

**Comment by LaugeGregers** [comment]
I too am experiencing this problem. I usually use three different keyboard layouts, swedish sv, danish da and US english en. Swedish is the primary one. In Swedish and Danish layouts, @ is typed as {ALT GR}+{2}.
When the keyboard layout is sv or da, auto-typing @ works, but when the keyboard layout is en auto-typing @ becomes 2.
I start KPXC manually after logging in. 
I tried allowing for different windows to have different keyboard layouts. It is the keyboard layout in the window being typed to that needs to be sv or da for the auto-typing to be correct, not the KPXC window.

 # Debug info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.1
Debugging mode is disabled.

Operating system: Fedora 30 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.1.12-300.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by anonymous133** [comment]
I have the same experience. 

As soon as I call setxkbmap us -variant colemak to switch keyboard layout to colemak, autotype does not work correctly anymore.

Switching manually to setxkbmap us before autotyping does fix the problem. So it would be great to have keepassxc check which keyboard layout is active before autotyping.

I'm using i3 and have different keyboard layouts on different workspaces to which I switch dynamically.

**Comment by mwip** [comment]
So, I ran into this problem again. However, now it is not with multiple but only one keyboard loaded. It is the standard German keyboard. 
Sys. specs: Arch Linux (Kernel 5.2.5) 
WM/DE: KDE Plasma
KeePassXC 2.4.3

**Comment by stefan123t** [comment]
I just want to add to the cause that it has something to do with the primary layout of your Desktop too. In the past my primary layout used to be us and secondary layout de.

I have been used to run KeePassX with this bug for years, i.e. I usually avoid z and y in newer passwords. Though when typing a password I am still used to switch to us layout first and then hitting autotype.

Now with a new system I installed (linux mint 19) I have opted for primary layout de and secondary layout us. This is when the problem with the @ in the username started to occur to me too, i.e. I get a q character instead.

After switching to KeePassXC 2.3.1 I have been digging your issues and reading up on the Qt Bug mentioned above. I guess this could be related, as apparently the primary layout chosen is somewhat changing the behaviour of the problem described.

using de as primary layout
layouts: de, us

de user.name@email.com  ist&bleibtg3h31m
de          ^ alt-gr+q     ^ shift+6
us user.nameqemail.com  ist^bleibtg3h31m
us          ^ (alt-gr)+q   ^ shift+6

using us as primary layout
layouts: us, de

us user.name@email.com  ist&bleibtg3h31m
us          ^ shift+2        ^ shift+7

de user.name"email.com  ist/bleibtg3h31m
de          ^ shift+2        ^ shift+7

**Comment by phoerious** [comment]
Perhaps it's also possible that your display manager's layout leaks into your session, which can be particularly problematic if KeePassXC starts early. This is one of the downsides of this whole legacy X11 stack that your display manager and your session are two totally different things and don't know a thing about each other. To this day I find it very difficult to make my login screen somewhat consistent with my session or my lock screen.

**Comment by stefan123t** [comment]
Regarding the layout switches I have made the above changes without quitting KeePassXC 2.3.1, hence the session information should remain. Though a shell expectedly returned different setxkbmap -query results after switching layout order in cinnamon-settings keyboard.

@phoerious I am running Cinnamon under Mint 19, hence I should only have libqt and KeePassXC in the play, though I do not know if that makes any difference. 

Having said that, switching the two layouts back to the old "us, de" order, I am used to the behaviour. Just wanted to note that the primary keyboard layout seems to play a significant and reproducible role in the way KeePassXC behaves on my system with multiple keyboard layouts.

**Comment by technodrome** [comment]
Also keep encountering this issue with customized layout. KXR does not respect at all what is entered in the password field. For example, if you swap `y` and `z` on your keyboard, it will type what it expects on the English keyboard which makes auto-typed passwords invalid.

I had to add dedicated EN keyboard to which I have to manually switch each time I want to use KXR! Great usability "feature", by the way.

Would make total sense to actually internally _switch_ to en-us keyboard while typing the password if KXR actually has such implicit requirement. This would be at least way better than ignoring this issue for non-English users for three years.

**Comment by phoerious** [comment]
We are not ignoring the issue. We are simply unable to reproduce it and therefore don't know how to fix it.

**Comment by stefan123t** [comment]
Dear @phoerius it should be sufficient to install two keyboard layouts in your desktop environment. I have given en and de as examples. You can use a custom dummy auto-type entry with a couple off passwords using special character that are located on different key locations on these two layouts, eg. „ and @ or q depending on your primary layout and use auto-type in a Texteditor for reproducing. Hence there is not much involved except KeepassXC, XKB and a huge pile of libraries.
Could it be the case that Keepass, KeepassX and KeepassXC use keycodes for Autotype and obfuscation instead of plain text letters ?
Kind regards,
Stefan
PS: I do not think you are ignoring this issue, just let us know if you still have problems reproducing. Maybe I need to detail the steps for reproduction?

**Comment by phoerious** [comment]
Thank. I was able to reproduce the issue with multiple layouts if the currently active layout is not the default layout. As soon as I move the non-English layout to the top of the list, KeePassXC picks it up and types the correct letters. This is pretty much what I noted before about layout switches. I'll see if I can find a fix for that.

**Comment by stefan123t** [comment]
Dear Janek,
I think you are right regarding the distinction between current active layout and default layout. I keep my fingers crossed so you can somehow query the current active layout from the OS / desktop env in order to use the right keycodes in auto-type obfuscation.
Kind regards,
Stefan

**Comment by ohnonot** [comment]
>As soon as I move the non-English layout to the top of the list, KeePassXC picks it up and types the correct letters. 

Interesting.
I wonder what that list is - something provided by the desktop environment you use?
I wonder if keepassxc expects a DE to be present and draw keyboard related info from that, and defaults to US if it can't find it?

I use no DE on Linux, English as UI language and a non-US keyboard layout.
I don't think I have a "list" of keyboard layouts:
```
$> setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     fi
options:    grab:break_actions
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete+xfree86(grab_break)
symbols:    pc+fi+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete+xfree86(grab_break)"	};
	xkb_symbols   { include "pc+fi+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
$> localectl
   System Locale: LANG=en_IE.UTF-8
       VC Keymap: fi
      X11 Layout: n/a
```

**Comment by phoerious** [comment]
KeePassXC uses your X keyboard map. If you have multiple layouts configured, of which one is selected dynamically via xkb extensions, it won't see it, since the order doesn't change. Your active layout has to be the first layout in the list.

**Comment by stefan123t** [comment]
Dear @ohnonot,
thanks for your reminder, as you are not using a DE to configure a list of keyboard layouts you are only having one layout, probably always the default, ie. in your case fi.

I just verified your queries on my system and I do have the list of layouts specified in both layout: us, de and xkb_keymap { xkb_symbols { include "pc+us+de:2+inet(evdev)+group(alt_shift_toggle)" }; specified.

$ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us,de
variant:    ,
options:    grp:alt_shift_toggle
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+de:2+inet(evdev)+group(alt_shift_toggle)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+de:2+inet(evdev)+group(alt_shift_toggle)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
$ localectl
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_DE.UTF-8
                  LC_MONETARY=de_DE.UTF-8
                  LC_PAPER=de_DE.UTF-8
                  LC_NAME=de_DE.UTF-8
                  LC_ADDRESS=de_DE.UTF-8
                  LC_TELEPHONE=de_DE.UTF-8
                  LC_MEASUREMENT=de_DE.UTF-8
                  LC_IDENTIFICATION=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

As you can see my primary layout of xkb_symbols is us and the secondary layout is de.

I have learned from the following Unix/Linux Stackexchange question that there are probably two ways to determine the current active xkb_symbol layout.

How do I get current keyboard layout?
https://unix.stackexchange.com/questions/12072/how-do-i-get-current-keyboard-layout

1) a small tool called xkblayout-state
https://github.com/nonpop/xkblayout-state

2) the LED status byte visible in set -q
This does work only for up to two layouts, though

I have double checked whether both would work by using a third layout (us,de,fi) as a tribute to your comment. While the former works the latter does only tell us whether we are on the primary layout or any secondary/third/... layout whatsoever.

$ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us,de,fi
variant:    ,,
options:    grp:alt_shift_toggle
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+de:2+fi:3+inet(evdev)+group(alt_shift_toggle)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+de:2+fi:3+inet(evdev)+group(alt_shift_toggle)"	};
	xkb_geometry  { include "pc(pc105)"	};
};

$ localectl
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_DE.UTF-8
                  LC_MONETARY=de_DE.UTF-8
                  LC_PAPER=de_DE.UTF-8
                  LC_NAME=de_DE.UTF-8
                  LC_ADDRESS=de_DE.UTF-8
                  LC_TELEPHONE=de_DE.UTF-8
                  LC_MEASUREMENT=de_DE.UTF-8
                  LC_IDENTIFICATION=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

us:
$ ./xkblayout-state print "%s"
us
$ xset -q | grep LED
  auto repeat:  on    key click percent:  0    LED mask:  00000002

de:
$ ./xkblayout-state print "%s"
de
$ xset -q | grep LED
  auto repeat:  on    key click percent:  0    LED mask:  00001002

fi:
$ ./xkblayout-state print "%s"
fi
$ xset -q | grep LED
  auto repeat:  on    key click percent:  0    LED mask:  00001002

@phoerious: Janek, would you be able and willing to compile a fix from the XKeyboard.cpp class given in the github ?

Kind regards,
Stefan

**Comment by stefan123t** [comment]
Dear all,

@droidmonkey so from the current analysis (multiple keyboard layouts/symbol xkb maps) I would say this is definetly a Linux only issue and can be ifdef'ed out for Win and probably also for Mac.

I do not know if the proposed symbol parser in the xkblayout-state tool would be also targeting users having reported this problem for manual changes using setxkbmap reported by @anonymous133.

But I assume that automatic layout changes depending on window focus as reported by @achilleas-k and @LaugeGregers are probably even out of scope for this fix, as KeepassXC would somehow need to get the target window's dynamic keyboard layout setting. But you are free to test the xkblayout-state wrapper from github to verify their use-case.

Kind regards,
Stefan

**Comment by ohnonot** [comment]
I must admit that the issue has not bothered me for a while, and I blurted out my previous comment without re-checking the facts.
It's (almost) always an interaction between kepassxc's autotype and mybrowser (Firefox), and I suspect that something has recently changed on both sides.
I have only one username that has an "@" in it, and that has worked as expected yesterday.
But my experience over time has been that this issue comes and goes...

And yes, I clearly have only one layout in "the list":
`xkblayout-state print "%S"
fi`
Note the capital 'S', it should list _all_ layouts.

**Comment by achilleas-k** [comment]
I haven't had the issue in a while, but I've also been using auto type a lot less (been using the browser plugin instead).

**Comment by stefan123t** [comment]
@ohnonot and @achilleas-k , thanks for feedback and double-checking on your side and the pointer to "the list" of layout symbols.
I have added another layout variant to my mix of layout symbols, ie. german with nodeadkeys.

$ ./xkblayout-state print "%s_%v"
de_nodeadkeys

xkblayout seems not fancy enough to print both layout symbols and layout variants in one line, but I guess we get the picture.

$ ./xkblayout-state print "%S %V"
us
de
de
fi
 

nodeadkeys


$ _

**Comment by ohnonot** [comment]
> I must admit that the issue has not bothered me for a while, and I blurted out my previous comment without re-checking the facts.
> It's (almost) always an interaction between kepassxc's autotype and mybrowser (Firefox), and I suspect that something has recently changed on both sides.
> I have only one username that has an "@" in it, and that has worked as expected yesterday.

And at least one more login that I know to have been problematic in the past.
Neither has bothered me for a long time; I have no idea whether keepassxc changed or firefox or both.
I consider the issue resolved.

**Comment by anonymous133** [comment]
Just to update you I still have this issue like reported already. No change on my side. I'm running KeepassXC 2.6.1

> I have the same experience.
> 
> As soon as I call "setxkbmap us -variant colemak" to switch keyboard layout to colemak, autotype does not work correctly anymore.
> 
> Switching manually to "setxkbmap us" before autotyping does fix the problem. So it would be great to have keepassxc check which keyboard layout is active before autotyping.
> 
> I'm using i3 and have different keyboard layouts on different workspaces to which I switch dynamically.
> 
> I'm on arch.
> 
> Initially colemak is my selected keyboard on boot which does work with autotype. But regardless if it is the active layout calling "setxkbmap us -variant colemak" again (even if it is already the active layout) breaks the autotype function in that it defaults to US layout.

**Comment by raphaelyancey** [comment]
For information, I fixed this issue on a stock Ubuntu 20 LTS install by only having one layout activated (instead of two). Might not be suitable for everyone though.

**Comment by technodrome** [comment]
> For information, I fixed this issue on a stock Ubuntu 20 LTS install by only having one layout activated (instead of two). Might not be suitable for everyone though.

That's not a fix. That's an unusable workaround from the long-term perspective.

**Comment by Jertzukka** [comment]
Running Keepass 2.6.2 and still experiencing the @ -> " bug with autotyping. I have only 1 keyboard layout set in my KDE and that is Finnish layout. I can verify that for me this bug only happens if KeePassXC is ran on Auto-start. If I exit the application and relaunch it, the auto-type works correctly.


<details>
 <summary>Specs</summary>

```
setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc86
layout:     fi
variant:    nodeadkeys
options:    compose:rctrl
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+fi(nodeadkeys)+inet(evdev)+compose(rctrl)
geometry:   pc(pc86)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+fi(nodeadkeys)+inet(evdev)+compose(rctrl)"  };
        xkb_geometry  { include "pc(pc86)"      };
};
```

```
localectl
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=fi_FI.UTF-8
                  LC_TIME=fi_FI.UTF-8
                  LC_MONETARY=fi_FI.UTF-8
                  LC_PAPER=fi_FI.UTF-8
                  LC_NAME=fi_FI.UTF-8
                  LC_ADDRESS=fi_FI.UTF-8
                  LC_TELEPHONE=fi_FI.UTF-8
                  LC_MEASUREMENT=fi_FI.UTF-8
                  LC_IDENTIFICATION=fi_FI.UTF-8
       VC Keymap: fi
      X11 Layout: fi
       X11 Model: pc105
     X11 Variant: nodeadkeys
```

```
Kernel: 5.9.10-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
Desktop: KDE Plasma 5.20.3 tk: Qt 5.15.1 wm: kwin_x11 dm: SDDM Distro: Manjaro Linux
 ```
</details>

**Comment by droidmonkey** [comment]
Just delay the start of keepassxc on boot.

**Comment by Jertzukka** [comment]
> Just delay the start of keepassxc on boot.

Thank you, it seems for me setting the autostart application to "sleep 5;/usr/bin/keepassxc" works around this problem.

**Comment by iromeister** [comment]
I have this problem for the first time for about a week now. I'm running LDXE on Gentoo and don't have the xkblayout-state command. How can I see the installed keyboard layout(s)?

**Comment by stefan123t** [comment]
@iromeister I had to compile it with the usual ./configure; make; make install according to their github repo:

**Comment by iromeister** [comment]
Now I installed and ran xkblayout-state, it shows only one layout "de". Restarting keepassxc does not change the behaviour.

**Comment by stefan123t** [comment]
@iromeister could you paste the output of
$ ./xkblayout-state print "%S %V"
and
$ setxkbmap -print -verbose 10 | grep xkb_symbols
?
Thanks, Stefan

**Comment by iromeister** [comment]
@stefan123t after a reboot it's working again. If the bug reoccurs I'll check back here.

**Comment by force1164** [comment]
Is it possible to simply add setting or something that would say I always want to use english keyboard layout? It drives me crazy when I have different layout and it writes e.g. "2" instead of "@" with czech layout. Either the auto-type should respect the keyboard layout set for Keepass or it should write the actual letters that are filled in the entry. Thank you :)
P.S. for more info click on the issue mentioned above #5890

**Comment by sindlarv** [comment]
It took me a while (and a few locked accounts for various services) to find out what's wrong and how to make this case 100% reproducible. But finally, I think I got it.

- First of all, locale in my Linux system is set to my native language (Czech) and use two keyboard layouts (CZ,US) with the US one being default
- I open my password vault (or create a new one, it doesn't matter) and make sure that keymap is set to US
- Then I create a new entry where username="test1234", password="1@3$5^7*"
- Set up KeePassXC to auto-type this entry to a text editor with sequence {USERNAME}{SPACE}{PASSWORD}
- Now, I switch to my editor and when I press the auto-type shortcut (and the keymap is still US), it's all fine and the output is "est1234 1@3$5^7*"
- However, if I switch to use CZ keymap and repeat the above, the output changes to "test+ěšč +2š4ř6ý8" (which is what you get if the original characters were typed in using CZ keymap)
- When I create new entry with keymap set to CZ (which is equal to my system locale), the output is fine with both keymaps

Therefore, my guess is that this problem has something to do with how the default (keymap, encoding?) is defined when a new password entry gets created. Not with the actual auto-type functionality. That's also why other people experienced different behavior over time and even report it as fixed, as in the meantime, they likely created new password entries with different keymaps and all of sudden it "worked".

**Comment by stefan123t** [comment]
@ghost the problem with auto-type is as far as i understand  that auto-type obfuscation is using keycodes instead of characters, ie the keycodes are fed into xinput before the keyboard layout gets a chance to translate them to characters. Depending on your current keyboard layout the keycodes will be translated differently.

Maybe it would be possible to circumvent this problem by disabling the obfuscation at least partly and only use characters instead of keycodes ?

@sindlarv could you check whether you have individual keyboard layouts per window enabled in your keyboard settings ? That would explain the description you gave for your problem to me.

I have worked around my problem in two simple ways:
1. I mostly use passwords without eg x and y using preferably unambiguous special chars, eg a dot
2. my keepass DB is locked with a password having at least one y in it. So I am forced to type using the correct (english) keyboard layout to unlock.
Auto type then usually works naturally.

**Comment by droidmonkey** [comment]
@stefan123t I can give this a try in my Auto-Type pr

**Comment by stefan123t** [comment]
@droidmonkey thanks, I have seen your closing comments in #474 and #2475 regarding IPC, however I truly believe that disabling the obfuscation using keycodes instead of characters might work. I am looking forward to your PR.
Thanks for this really nice tool, I do advocate its use over Keepass and KeepassX =^D

**Comment by phoerious** [comment]
There is no "obfuscation" going on.

**Comment by hifi** [comment]
Yesterday I opened a PR to fix the requirement to switch layouts before auto-type and I encountered the _other_ bug of layout switch breaking after a single auto-type run.

However, today I can't reproduce it at all. It happened to me all the time back then but even on the same machine I can't reproduce that exact issue again.

Does anyone know what exact combination of keyboard settings I need to reliably reproduce the broken layout switch shortcut behavior? I tried all sorts of combinations and timings to reproduce it tonight to no avail. I would gladly try to fix it if I can get a reliable repro case for myself.

**Comment by stefan123t** [comment]
> There is no "obfuscation" going on unless perhaps you mean that anything programmed with the libX11/Xkb API looks naturally obfuscated.

@phoerious I was referring to a Keepass feature above. Though I do not know whether obfuscation is supported in KeepassXC too, I assumed the basic Auto-Type feature just works the same in KeepassXC. Thanks for your clarification.

**Help Introduction: What is Two-Channel Auto-Type Obfuscation?**
https://keepass.info/help/v2/autotype_obfuscation.html
The Auto-Type feature of KeePass is very powerful: _it sends simulated keypresses to other applications_. This works with all Windows applications and for the target applications it's not possible to distinguish between real keypresses and the ones simulated by Auto-Type.

**Comment by phoerious** [comment]
I know what TCATO is and it's kind of useless and giving users a false sense of security.

**Comment by stefan123t** [comment]
@phoerious yes, I just wanted to state clear that I have mistaken TCATO with the simulated keypresses, i.e. keycodes used for normal auto-type.
These X11/XKB keycodes already looks a bit "obfuscated" and this is the probable cause for the active setxkbmap keyboard layout setting to mingle with the interpretation of those keycodes issued by KeepassXC converted into characters when typed into the target application window.

**Comment by hifi** [comment]
@stefan123t If possible try #6247 if it helps with the wrong layout being used. It's not yet ready for merge but it should have the right idea how to solve that.

I was looking into information about the layout change hotkey (like alt-shift) not working after auto-type has been issued.

**Comment by hifi** [comment]
I believe both issues are now fixed with #6247. If anyone could test it that would be great!

**Comment by stefan123t** [comment]
@hifi I tried to checkout the pull request #6247 using github but did not succeed.
```
$ /snap/bin/gh pr checkout 6247
fatal: Unable to find remote helper for 'https'
exit status 128
```
How do I best checkout your PR and commit selectively ?

**Comment by droidmonkey** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by stefan123t** [comment]
@droidmonkey thanks for the pointer, I got it to checkout with the debian packages of github and following the description on the your wiki to install all the qt5 dependencies it compiled fine.
Is 2.7.0 going to stay this way or did I forget some Qt compile options ?
For me it takes a lot of screen estate (even in View > Compact mode!) and the native Linux Mint/Debian version 2.4.3 is a lot less space hungry.

![Screenshot from 2021-03-13 22-58-35](https://user-images.githubusercontent.com/11159753/111051003-4d0ed580-8450-11eb-8c92-6d40818b364c.png)
![Screenshot from 2021-03-13 22-57-31](https://user-images.githubusercontent.com/11159753/111051004-4da76c00-8450-11eb-8603-5e2028b27e8c.png)

@hifi, thanks for the pull request #6247.
Regarding #324 it does auto-type the correct sequence for all us, de and fi keyboard layouts I configured.
I.e. there were some additional questionmarks raised by @ohnonot regarding a third layout could be detected correctly earlier in this issue.

```
$ setxkbmap -print -verbose 10 | grep '\(layout\|xkb_symbols\)'
layout:     us,de,fi
	xkb_symbols   { include "pc+us+de:2+fi:3+inet(evdev)+group(shift_caps_toggle)+group(lalt_lshift_toggle)"	};
```

us: `myname@mydomain.tld	passwordwithZ,Yand@`
de: `myname@mydomain.tld	passwordwithZ,Yand@`
fi: `myname@mydomain.tld	passwordwithZ,Yand@`

@hifi, I am looking forward whether this will also solve the issue with the Alt+Shift key combo for switching the keyboard layout not working sometimes ?
I do experience this also from time to time, but could not attribute it to the Keepass auto-type option yet.
I though it has something with a Citrix client who does not always behave quite well.
Do you have a test case, where this is reproducible and is there an issue ?

**Comment by hifi** [comment]
#6247 should work with any number of layouts that X can simultaneously have enabled. It will also prefer your current layout during typing but will switch it on-the-fly if a symbol is only found in some other layout. If you have an indicator on some panel which layout is active and you have slow enough typing delay for Auto-Type it should be visible that the layout is changing automatically on demand.

However, it does not work if you try to use a symbol that is not within any of your configured layouts but that's a tradeoff I'm willing to make for code cleanliness. It makes issues like #3422 an edge case that will regress slightly as I couldn't find a keyboard layout combination that had all of the symbols used in the example and it will instead just skip/ignore them. I did get most of them out by adding a couple of large layouts.

I haven't been able to reproduce the layout switch toggle not working after Auto-Type consistently enough I could debug it. Though if #6247 happens to fix it as well I'm not very keen to debug it further either so testing it for longer periods of time where you usually get the layout switch breaking issue would be nice to know.

I hope we can get most Auto-Type issues on Linux that are fixable done for 2.7.0 as Auto-Type has received a major overhaul in UX as well.

**Comment by the-wolfman** [comment]
guys, very good to hear that. I am out of my depth here, so please excuse a frank question: 

Does this also affect the issues with auto-typing into a virtualbox or the like instance running linux guests? 

No clue how linux handles keyboard layouts at boot time. Something like grub config during e.g. password entry for luks encryption and session manager config at login screen?

**Comment by hifi** [comment]
@the-wolfman If you had problems with incorrect characters typed in VirtualBox then it may help. I added an AppImage download as a comment to #6247 if you can test it.

**Comment by the-wolfman** [comment]
ok, missed that AppImage. Will try on Wednesday as I am travelling and need to set up a test host. On a side note, most of the problems seem to occur when using Windows as a host, as mentioned in issue #1833, which I can confirm. If, by chance, you've created a Win64 Portable as well, I can also test that.

**Comment by droidmonkey** [comment]
The fixes made by Hifi only apply to linux

**Comment by stefan123t** [comment]
@the-wolfman this issue spplies to Linux platform and Auto-type in native X windows only.
That is the same symptom could be experienced on any combination of differing keyboard layouts used in VMs, etc. but as the KeepassXC outside a VM can not easily know the layout set and used inside the VM, a mapping is not possible, except you are using the same within and without.

**Comment by the-wolfman** [comment]
Thanks, your comments nudged me in the right direction. Still way out of my depth though. 
Anyway, I followed up on the issues I encountered in that context and am convinced that on my linux host, my kind of mixed locale settings, especially the combination of LANG=en_US.UTF-8 with other languages in the LC_% values, as well within and between host and virtual instances was causing the trouble. I worked around it intuitively till now without understanding it. 
fwiw, out of curiosity I also did some tests with a Windows Virtualbox host and strongly believe the overall way keypresses are treated by Virtualbox on Windows is making the difference. Some passwords, even simple base(x) variants or numbers can fully lock up keyboard input for Virtualbox instances without them even getting to the guest.

**Comment by mizapf** [comment]
I noticed that from time to time, my username or password was incorrect when using autotype. When I found this bug report, I checked a bit deeper and saw that autotype actually dropped all occurances of "z" in the username or password. As you can see, my username contains a "z", and I am of course using a German keyboard layout, so I cannot avoid this issue by e.g. choosing another password.

However, the problem never occurs from the start. When I launch my Plasma/KDE system and have KeepassXC autostarted, there is no problem, all characters are filled in, including the z. After some unknown time of use, the issue shows up, and since I only notice it on the next attempt to fill in a login form, I don't know what causes the problem.

In that case I have to completely stop KeepassXC and restart it. Then, autofill is working again.

**Comment by hifi** [comment]
@mizapf can you reproduce the issue with a 2.7 snapshot? Linux Auto-Type is completely revamped in it.

**Comment by stefan123t** [comment]
Dear Michael,
the problem is solved for the 2.7 versions by the Patch from Toni @hifi 

The problem occurs in previous version if you have multiple keyboard layouts (english, german, etc.), which you can switch using the Desktop environments helper tasklets (the flag symbol) or eg. Shift+Ctrl as a hotkey on some systems.

Please make sure to use only one or at least the same, primary keyboard layout throughout the KeepassXC usage, in case you are troubled by this problem. Or upgrade to the latest keepassxc 2.7 snapshot release where this is fixed.

You can always check which keyboard layouts are currently set:

setxkbmap -print -verbose 10 | grep layout

Kind regards,
Stefan

**Comment by Nishi** [comment]
Was this auto-typing issue resolved for all OSes, i.e. for Windows 10 as a host OS as well?

KeePassXC 2.7.1 doesn't work for me in this regard - in contrast with KeePass Classic as old as version 1.31.

**Comment by droidmonkey** [comment]
This was a Linux only bug. On windows if you type into a virtual machine you'll have problems, otherwise it works without issue as far as we know.

**Comment by dok18** [comment]
@stefan123t  @droidmonkey 

This is happening to me with newest version (KeePassXC-2.7.1-x86_64.AppImage). I am on Ubuntu.

It does not happen with KeePassXC-2.5.3-x86_64.AppImage which I used until today.

Layout:
$ setxkbmap -print -verbose 10 | grep layout
layout:     at


I have no other keyboard layouts or whatsoever. Basicly is uses for some rease on QUERTY instead of QWERTZ.

Any ideas what to do here?

**Comment by droidmonkey** [comment]
@hifi

**Comment by hifi** [comment]
Umm, try running `setxkbmap` once and see if it happens, though there should be a workaround for that in KeePassXC that avoids it.

**Comment by dok18** [comment]
Running 

$ setxkbmap de -option grp:alt_space_toggle

"fixes" this. Still interesting, that I dont have this problem with KeePassXC-2.5.3-x86_64.AppImage, but it exists with KeePassXC-2.7.1-x86_64.AppImage.

**Comment by stefan123t** [comment]
@dok18 sorry for being late to the ~~party~~/issue:

Would you mind running the following _before_ **and** _after_ your workaround in order for us to understand what has been changed in your xkbmap ? Please make sure that _before_ the workaround the problem still is reproducible. Thanks

`$ setxkbmap -print -verbose 10`

Also please make sure to give us some detail about your system e.g. using

`inxi -F`

other than that we may be able to get some more information from looking at the results of your current xkblayout-state (you need to compile that from source)

`xkblayout-state print "%s"`
