### ISSUE TITLE
Option to not minimize after auto-type

### ISSUE THREAD

**Issue by stingray21** [keepassxreboot/keepassxc#3457]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When KeepassXC is not minimized and auto-type is performed, KeepassXC should remain open (not minimized)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC minimizes after auto-type

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Add option in settings for auto-type, like the one for copying ("Minimize when copying to clipboard")

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. KeepassXC is not minimized
2. auto-type (key-binding or button)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.0
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.1.21-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by zoomorph** [comment]
Should be an option not to minimize after auto-type. Otherwise database is locked every time you auto-type, if you have enabled the option to lock on minimize.

**Comment by amkuchta** [comment]
I second this - if I am logging into a few different sites at once (which happens really frequently), I don't want to have to re-open the KeePassXC window each time.  I use the browser integration, when available, but for some sites, the URL changes after the initial navigation and cannot be tracked by KeePassXC.

**Comment by irgendsontyp** [comment]
The KeePassXC window has to be hidden in order to bring the destination window to front, right?

Would the solution here be to re-show the main window when auto type has been done?

**Comment by tsdmgz** [comment]
macos behavior was, if on full screen, was to send a cmd+tab and then autotype without minimizing (probably a side effect of being in its own desktop). that said i'm fine with bringing the window up again when autotype is done.

either that, or making it as an option?

**Comment by jrobert-gh** [comment]
I also vote for this, for reasons already stated. Thanks.

**Comment by auwsom** [comment]
My cynicism suspects most of the devs use fancy macs, and as stated dont have this problem. So much for being able to conveniently minimize to close the db. Unset that setting if you want to be able to use autotype and dont want to enter in your password again everytime after hunting for the window to restore.

**Comment by droidmonkey** [comment]
@auwsom I use a fancy Dell running Windows 10... which I use to make this project even possible for you to use in the first place.

**Comment by auwsom** [comment]
Hi Johnathan,

Fair enough, thanks for showing you're aware of this issue.

Appreciate the work that you've done and do. Will probably edit that
comment to be better. So many tools I use are designed poorly and worse
have no channel for real feedback. Sorry if that spilled over here.

So do you use exit on minimize? And autotype? Do you see the value of being
able to use both?

**Comment by auwsom** [comment]
Also, curious if KPXC considered using QtSharp to port over existing KP using mono on Unix-based OSes? It seems like that would have avoided the 'regular KP can, why cant KPXC' issues, if it was available when this project began. Mono does seem to run well.

**Comment by droidmonkey** [comment]
Lock on minimize also impacts copying to clipboard (tracked in #1090). I generally do not recommend having that setting enabled at all, it is overly agressive for most use cases. You would be far better off setting a shorter lock after inactivity time,

**Comment by auwsom** [comment]
Jonathan, thanks again.. (I didnt mention plugins.. the OG KP can show you duplicate passwords which allows you to manually delete one of two 'conflicting' entries, if the DB has been edited in different locations, say on Android and on PC. This allows the conflicts to be resolved transparently without a 'brute-force' and 'black-box' sync. No plugin required. This especially useful with a PWD MGR because the DB would have to be exported to use regular comparison tools and then imported back again.

..I did edit a reply above that you might not have seen saying the value in using Lock on Minimize is having 'visual indicator the DB was locked when the window was not visible'.. it is a tangible way to always know if the DB is unlocked or not (a color change on the taskbar or systray icon would do the same, may be difficult cross-platform though, but maybe not with Qt). 

re #1090, I guess thats another reason why I always keep the window visible when Im jockeying into different accounts, usually on browser restart. Sometimes I'll even edit an entry with a space character just to prevent the DB from autolocking after 20 min, if Im upgrading a bunch of passwords or something. The whole time I know that as soon as I click Apply or Cancel and then use a gesture to fling the KP window to the tray, the DB will be locked and safe.. Whereas as long as I see a corner of the window in the background, I know its still unlocked. Visual confirmation is always more robust than a timeout setting IMO.   And honestly, I'm not sure why anyone expects a password to stay in the clipboard after the DB is locked, that seems like a security hole. The underlying problem seems to start with the conflict of Autotype Minimize and Lock on Minimize. The simplest resolution seems to be to use AltTab to switch windows instead of minimize, as it is assuming the least about the intentions of the user (ie, that they want the window minimized). As other posters above report, it is a hassle to unminimize, at least in _ubuntu, because usually the minimized windows are not included in AltTab switching, and forces user to hunt for the taskbar icon to click (ie more carpel tunnel for every Autotype)..

**Comment by droidmonkey** [comment]
FWIW, we do show a different taskbar icon when the databases are locked.

**Comment by auwsom** [comment]
hmm.. no color change on Kubuntu 18.10.

Also, to be fair, it looks like the AutoType Minimize behavior is inherited from the OG KP. Again maybe a Windows thing, as I never used to use AutoType in Windows, do people AltTab back to KP to use it again?

**Comment by Tomatenjoghurt** [comment]
> Also, to be fair, it looks like the AutoType Minimize behavior is inherited from the OG KP. Again maybe a Windows thing, as I never used to use AutoType in Windows, do people AltTab back to KP to use it again?
Nope, OG Keepass does exactly the same when run on Linux with Mono. Used OG Keepass for work with Windows for a long time now and can confirm, that it does not behave like this on Windows. Keepass XC, however, minimizes on Windows and Linux (Mint).

**Comment by auwsom** [comment]
I'm a little confused by that message.. you say KPXC 'however' *does*
minimize on both, meaning that OGKP does not? I just tested again KP2 on
Kubuntu and it does minimize. I'm assuming it does the same on Windows, but
was asking to confirm. I read the first part of your message to mean it
does not use tab switching, until I get to the word 'however'..


So are you saying OG KP does not minimize on autotype usage on Windows or
Linux?

In that case, this would add support that the least assuming action by KP
was and should be to simply switch tabs, so that the window doesn't need to
be restored from the tab bar or tray.

**Comment by Tomatenjoghurt** [comment]
@auwsom Sorry, maybe I was unclear or mixing up stuff.
Yes, on Linux Keepass 2 **does** minimize. I always believed this is due to the autotype implementation on Linux (as you need to install xdotool).
On Windows Keepass 2 **does not** minimize.

Keepass XC minimizes on Linux and Windows.

**Comment by auwsom** [comment]
Hi and thanks.

Since Minimize after Autotype was not on the original KP using WIndows for
which it was originally designed for, I would repeat my assertion:
this adds support that the least assuming (and therefore most
flexible/powerful) action by KP was and should be to simply switch tabs
after Autotype, so that the window doesn't need to be restored from the tab
bar or tray.

**Comment by brianmercer** [comment]
There is already an option for minimize, drop to background, or do nothing when copying to clipboard.

It would be nice to have a similar option to drop to background on auto-type instead of minimize.

**Comment by damaltor** [comment]
+1 for this. I use KeePassXC on two PCs which have two monitors, both PCs have to be logged in in the morning into multiple services, which means that i have to reopen the window multiple times. Also, some sites allow only entering of the email and entering of the password on a second page, so that is two reopens for one login. putting a long delay between username and password would maybe be an option, but is not very reproducible. i could simply hold KeePassXC open on the second monitor, and login one ofter another, i would not need the minimize function and would like to disable it.
Browser integration is nice, but as said earlier, is not always working.

also, for compatibility reasons, it might be easier to minimize, auto-type, and reopen.

**Comment by phoerious** [comment]
TBH, I am not even sure if this even possible. On some systems we may be able to raise foreign windows, but current Auto-Type relies a lot on the order in which your system activates the next window when ours is minimised or hidden. Perhaps it's possible to move ourselves to the bottom of the stack, but I'm not entirely certain about that.

**Comment by damaltor** [comment]
Hmm as long as the program is still running, i dont know why it should not work. it could minimize, autotype, and un-minimize after that, just like any other program that is minimized and wants your attention. alternatively, defocusing the program might work as well, and refocusing would be possible too.

**Comment by droidmonkey** [comment]
It sounds easy, until you implement it and realize every OS has a unique problem that prevents you from being 100% successful....

**Comment by damaltor** [comment]
I know, i know, i am a software developer myself. Still, this would be a nice feature, and as minimizing already is implemented, reopening should not be that far of a stretch - at least i hope so. activating the other window is handled by the operating system anyway, i think. I really hope that that is not a huge thing to implement - at least it sounds kinda simple, though i learned in my years that "sounds simple" not always means "is simple to implement" :)

**Comment by droidmonkey** [comment]
I don't think this will be a big deal, although we have seen elsewhere where the window is not given focus again correctly. This is certainly easy to turn on, then we'll have to test it

**Comment by Caralluin** [comment]
This would especially be useful for "special" auto type-actions (only username or password) - I find those quite useful for special cases e.g. when changing a password, but then you usually have to re-type the new password, so you need to switch back again.

It would also feel consistent to have the same settings as for the copy-behaviour (although I see, that implementation is quite more difficult to get platform-independent).

**Comment by droidmonkey** [comment]
This is much less an issue with the new Auto-Type dialog in 2.7.0. You can press ctrl+1 or 2 to type username and password, respectively.

**Comment by phoerious** [comment]
I think this is to difficult and unsafe to implement and with the new Auto-Type dialog it's pretty much a non-issue.

**Comment by climb-on** [comment]
I don't understand at all why this would be unsafe.  And for me it's definitely an annoyance.

I'm running KeePassXC 2.7.4 on Mac OS X 10.15.7.  I like to keep KeePassXC open - often on a second monitor.  Typically I use Shift-Cmd-U to open a new browser window, and then when I'm sure I am at the login page, I use Shift-Cmd-V to login.  When I do this, KeePassXC minimizes, which is not what I want.  I'd rather keep it open so I can open and login to additional websites.  I realize there are other ways to use KeePassXC that might obviate the need for this, but is there anything wrong with using it this way?  

Seems like it would be very easy to add a preference "Don't minimize after auto-type" and I can't see why this would be unsafe.  

My request would be to reopen this as a feature request, or let me know if I'm using the tool in an unsafe way.

Thanks.

**Comment by droidmonkey** [comment]
There is a potential that the OS could ignore our request for the target window to be in focus. I guess the user can deal with that problem when this feature is enabled.

**Comment by damaltor** [comment]
That would really be great. Thanks for reopening.
Also, if the os would ignore the target window in focus, the credentials would be typed into keepassxc in the worst case, wouldn't it? That would be weird, but not very unsafe, I guess. It would probably be unsafe if the os brings a _different_ window in focus, but that could happen on minimizing keepassxc as well.

**Comment by droidmonkey** [comment]
We have a fail safe that prevents typing into the keepassxc window

**Comment by damaltor** [comment]
Oh, great. I did not know that.

**Comment by christian-reiter-sbm** [comment]
I vote for this. Would be great to have this feature.

**Comment by AurelienBISOTTI** [comment]
Any update on this ?

I had to fight against Ubuntu to find and disable "tile groups" that was messing with the window focus, just to find there is a non-disablable and by default auto-minimize after auto-typing in KeepassXC.

**Comment by cwoelkers** [comment]
While not minimizing would be nice how about instead of an option to do that there is an option to automatically restore(un-minimize) the window instead. I would see it working like this.
You start the auto-type, KeePassXC minimizes, auto-type does it's thing, the KeePassXC window is restored to its pre-minimized size and location.

**Comment by damaltor** [comment]
Should work, too. I just would like to have a way to have KPXC open after autotyping. On one screen, minimizing and un-minimizing should work fine.

**Comment by cate02** [comment]
all these years of yapping yet still no dont-minimize after auto-type 😭

**Comment by jrking78** [comment]
This feature would be very nice. When you have 2 monitors and have KeePassXC on the other monitor, it is annoying to have it constantly minimizing. Thank you for considering it!

**Comment by handkerchief333** [comment]
In my opinion, the KeePassXC should never be minimized unless I explicitly minimize it manually. Anything else is patronizing. But as soon as the "Browser Access Request" pop up appears, if I click on the X or "Allow Selected", "Deny All" etc. KeePassXC is always minimizing, and that is very annoying. Because then I have to call it up manually again and again, x times a day. 

it would be great if there was an option, with the appropriate security informations (if this is a security problem). “Minimize KeePassXC manually only".

**Comment by droidmonkey** [comment]
I believe that issue with the browser minimization was corrected for the next release.

**Comment by sccfit** [comment]
Excellent, thanks! I originally used Keepass (Mono) before switching to KeepassXC several years ago, and I've sorely missed this feature ever since.

**Comment by Midtempo-abg** [comment]
It's been two months since the post saying, "that issue with the browser minimization was corrected for the next release" and my KeepassDX still has no option to not auto-minimize.  I'm not sure if KeepassDX has had an update in the past two months.  The version I am using is 2.7.6.

**Comment by droidmonkey** [comment]
We are KeePassXC and we are on version 2.7.10.

**Comment by jrking78** [comment]
But this issue is still not added right? My KeePassXC is up to date and it still minimizes. I am on a Mac and am really looking forward when this will be an option to disable. Thanks for all you do!

**Comment by droidmonkey** [comment]
The comment had nothing to do with this issue, unfortunately

**Comment by wesnm** [comment]
This would be a very helpful addition. When using autotype and nested RDP sessions, even the global hotkey doesn't work. The parent RDP session has the same window name, so that can only be associated with one entry. And jumping back to the last active window doesn't work because keepassxc minimizes itself, and if the RDP session is full-screen, you have to minimize it as well, so the window order is off. I would rather just hit autotype and manually tab back to the session.

**Comment by flagellatedcucumber** [comment]
This feature request is still outstanding.  Now on KeepassXC 2.7.11, running on Utunbu Linux, and still KeepassXC arbitrarily minimises after auto-type.

I can't think of any good reason why anybody would _want_ a password manager to disappear from the user's focus half-way through a job.  It's 2025, nearly 2026: logging into anything nowdays now requires multiple uses of password managers, sometimes a smartphone, a blood-sample, a sworn declaration of fielty to the Cult of Identity™ etc etc).

This feature request is long overdue fulfilment and is fast becoming a bug (because what the app delivers is no longer what is objectively, and generally, required, i.e. a _design_ bug)

**Comment by droidmonkey** [comment]
Uhhh just use global Auto-Type

**Comment by jrking78** [comment]
I don't want to complain, and am very thankful for all the programers that make this available as open source, but this would be so nice. I deal with this almost every day. I have thought about looking for something else just because of this issue. Every time I hit the auto type, it minimizes. I work from a MAC and use stage manager. The next time I need KeePass XC, it is not in my running tasks (Stage Manager), so I have to hit the option to open a program, then type keepass xc, then maximize it just to get back to my passwords. It would be so nice if this feature could be added soon. I thought it was something that was planned for, I have been checking back here on a frequent bases hoping it would be fixed soon?

**Comment by wesnm** [comment]
Global auto-type doesn't work in some scenarios, because it relies on window names as mentioned in my previous comment. I end up just using my phone with keepassdroid + inputstick instead of keepassxc, but I would prefer this solution.

**Comment by flagellatedcucumber** [comment]
> Uhhh just use global Auto-Type

Global auto-type does not resulted in the desired outcome (it creates its own issues in a multi-user, multi-app, commercial environment).  It offers no viable workaround.  The root problem is the automated minimising of the app after auto-type.  The root problem needs resolving head-on.

**Comment by theking2** [comment]
I frequently need access to totp after autotype. It is tedious to find  keepassxc again to <kbd>ctrl</kbd>+<kbd>t</kbd>.

**Comment by damaltor** [comment]
You can alt+tab to get keepassxc back. I'd still want to have it to stay open

**Comment by wesnm** [comment]
> You can alt+tab to get keepassxc back. I'd still want to have it to stay open

This is obviously what people are doing right now. I don't know about on a Mac, but on Windows, sometimes the window goes to the far end of the alt-tab list. This can be quite a few alt-tabs to get back to it. And if you have minimize to system tray enabled, it's gone completely and you have to re-open it from the tray.

**Comment by Fry-kun** [comment]
I'm on Fedora Linux and I have the same issue.
Minimized windows locks the DB and I have to unlock it again and again, very disruptive!
It's currently easier to CTRL-C/V and Alt-Tab back and forward several times because of this behavior

**Comment by thalunil** [comment]
Disabling the minimize after auto-type is in my opinion also a useful thing.
I find it annoying and disruptive too.
