### ISSUE TITLE
Toggle for visibility masterkey to remember the previous choice

### ISSUE THREAD

**Issue by littlefoodt** [keepassxreboot/keepassxc#3786]
## Summary
The toggle for password visibility on the masterkey screen doesn't remember your previous choice. I'd like it if it would. 

## Desired Behavior
Keepassxc remembering that I previously turned on the toggle for password visibility at the masterkey screen. (And possibly a checkbox in settings that could turn this on/off for users that need visibility off.)

## Context
Right now when I start up keepassxc I just go ahead and start typing the password, then I realize my fingers were faster than my brain and I turn the visibility on and just have another go. I usually only use this pc at home, so visibility is not a key security feature for me.

I understand for some users it may be very awkward when they forgot that their toggle was on and visibly wrote out their entire masterkey in public. Maybe we could add a little warning sign or better yet, some checkbox in the settings that would turn this feature on or off. 

ty for reading!

**Comment by phoerious** [comment]
I am very inclined to close this as a WONTFIX. Remembering that choice can expose you to shoulder surfing while entering the password in a different environment without remembering to toggle it back before entering the first few characters. Displaying the password on-screen should always be an explicit and deliberate action.

**Comment by littlefoodt** [comment]
I do understand that sentiment, for the most part this is true. However there's got to be lots of people who only use their machines at home and do not have someone shoulder surfing (as stated, I don't have that issue myself).  Now the toggle button itself isn't exactly huge and is also far away from where you'd usually go/keep with your cursor, so the action to turn this on every time feels pretty invasive to my workflow.   
A checkbox in the settings that would allow the users who aren't worried about other people looking at their screen would be enough to keep this feature 'off' for everyone, but being able to turn it 'on' would save me a few clicks/moves several times a day. 
(Leaving the database unlocked would be the option, but it would be far less secure in case someone decides to break into my home and hit me over the head.)

**Comment by droidmonkey** [comment]
There is no password interface in the world that starts off in "reveal mode" in any application I have ever used. I especially don't want that behavior in a password manager.

**Comment by littlefoodt** [comment]
> There is no password interface in the world that starts off in "reveal mode" in any application I have ever used. I especially don't want that behavior in a password manager.

As stated, it would be best for this to be an opt-in feature rather than an opt-out. This would ensure that people only turn this on if it benefits them and they deem it secure enough. 
Besides, reveal mode doesn't start until I start typing. In the rare occasion my main working laptop would be traveling with me to another location with possibility of shoulder surfing, I'll gladly take the responsibility of having to remember to turn the toggle 'off' first. Which I'm guessing would be the case for a lot of people that work from home on desktops or laptops that don't ever leave their spot.

**Comment by droidmonkey** [comment]
In 2.5.1 I fixed the visibility button to always focus back in the password field

**Comment by merwok** [comment]
>  you'll be back in the password edit.

I saw that change recently and am still getting used to it (as well as the big overall style change — too bad to lose my global style for one app).  However I can’t tab onto the :eye: icon anymore, so I have to interrupt typing to use the mouse and click there.

**Comment by droidmonkey** [comment]
Ctrl + H
