### ISSUE TITLE
keepassxc-cli extract to write password prompt on tty instead of stdout

### ISSUE THREAD

**Issue by JulienPalard** [keepassxreboot/keepassxc#4379]
I would like to be able to diff two keepassxc databases (yes, I diverged one on two laptops...).

## Expected behavior

I tried `diff <(keepassxc-cli extract left.kdbx) <(keepassxc-cli extract right.kdbx)`, but the password prompt is being written on stdout, so I don't get it, see:
```
write(1, 0x5570c102b1f0, 46Insert password to unlock left.kdbx: )            = 46
```

I tried `keepassxc-cli extract left.kdbx > left.xml` but again, password prompt is written on stdout, so It's written in `left.xml`, and not displayed to me.

Yet typing the password blidnly works, as the process reads correctly on stdin.

## Expected behavior

I would like for `keepassxc-cli extract left.kdbx > left.xml` to display me the password prompt, and not store it on left.xml.

## Possible solution

I think the password prompt should be written on the tty, like ssh does for example:
```
openat(AT_FDCWD, "/dev/tty", O_RDWR)    = 5
write(5, "localhost's password: ") = 23
```

## Steps to Reproduce

```
keepassxc-cli extract left.kdbx > left.xml
```

Either kill the process, the password prompt is written in left.xml, or type your password, the password prompt then the full xml is written in left.xml.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.5
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.4.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Fixed in 2.5

**Comment by amid-flood** [comment]
I'm running 2.5.4 on Manjaro, and I am still seeing this behaviour.

**Comment by droidmonkey** [comment]
Upgrade to 2.6.0
