### ISSUE TITLE
Keepassxc changes owner and group of kdbx file

### ISSUE THREAD

**Issue by Francois04t** [keepassxreboot/keepassxc#4543]
usecase : one database for multiple users under linux

I created a group datafr. I added the users to that group. I changed the group of the kdbx database to datafr. The database' owner is user1
ls -l :
-rw-rw-r-- 1 user1 datafr 42078 avril  3 16:13 base.kdbx

## Expected Behavior
[NOTE]: when user2 accesses the database and modify the database, the owner:group should not be changed. It should remain user1:datafr

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
when user2 accesses the database and modify the database, the owner:group is changed to user2:user2. WRONG
when user2 accesses the database and don't modify the database, the owner:group is not changed. that's correct

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # 
Happened under linux Kubuntu LTS 18.04

[NOTE]: # 
1. create a group datafr. 
2. Add the users user1 and user2 to that group
3. user1 create a database base.kdbx
4. change the group of the kdbx database to datafr
5. verify owner:group of the kdbx database. ls -l should produce:
-rw-rw-r-- 1 user1 datafr 42078 avril  3 16:13 base.kdbx
6. log in as user2
7. modify the kdbx database with keepassxc and save
8. check the owner:group of base.kdbx

## Context
[NOTE]: #
Happened under linux Kubuntu LTS 18.04
see previous case (and tagged not a bug !!! ;) )
Same database file for several local users #415

## Debug Info
[NOTE]: # 
KeePassXC - Version 2.3.1
Révision : 2fcaeea

Bibliothèques :
- Qt 5.9.5
- libgcrypt 1.8.1

Système d’exploitation : Ubuntu 18.04.4 LTS
Architecture processeur : x86_64
Noyau : linux 4.15.0-91-generic

Extensions activées :
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Permissions and ownership are entirely separate, as you know. Do you have safe saves disabled? If so, enable safe saves to see if that retains ownership.

With that said, we do not do anything special in the code regarding either ownership or permissions.

**Comment by genbtc** [comment]
This behavior sounds like a typical scenario of: when rewriting the file, a NEW db file is created (by default with the current user2:user2), and the file is NOT actually modified in place (where it keeps its attributes). 
This can be further investigated by running "stat" on the database before and after, and watching to see if the Inode changes. Lots of programs perform this save process as : "write to a tmp file, make sure it wrote correctly, now theres 2 copies of the DB, delete old copy, rename new temp file to the old name". This is correct, however this is at odds with the UID/GID/perms, when nothing is done about it. 
There probably Should be some special handling.Multiple user-groups security model working successfully is important.

**Comment by phoerious** [comment]
Atomic saves should preserve file permissions. If those are off, there may be issues.

**Comment by droidmonkey** [comment]
This is a Qt bug: https://bugreports.qt.io/browse/QTBUG-56366

**Comment by droidmonkey** [comment]
This was fixed in 2.6.6

**Comment by julianwiedmann** [comment]
> This was fixed in 2.6.6

@droidmonkey Any chance you could point at the commit? Thanks. I'm running 2.6.6 and believe I'm still seeing this bug. The 2.6.5...2.6.6 diff also doesn't contain any obvious fix candidate.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/6363

**Comment by sertonix** [comment]
#6363 didn't fix the issue. It just changes the permissions of attachments.
But the issues is the owner and group of the database file.
The issue still exists and therefor should be reopened.
