### ISSUE TITLE
URL matching is still broken

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc#4754]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When having two different accounts for two different parts of the same domain, KeepassXC won't distinguish them properly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry FOO with the URL https://example.org/foo
2. Create an entry BAR with the URL https://example.org/bar
3. Request logins for one of those URLs

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

For each request, I only get one result, and it is the correct one.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Keepass asks me for permission for *both* entries, regardless of the URL. Also, it will always return the *same*  password regardless of the provided URL.

## Context
[NOTE]: # ( Give us any additional information you may have. )

I'm requesting the entries using the Python API. I'm inventing URLs for a domain I own as a workaround until https://github.com/keepassxreboot/keepassxc-browser/issues/533 is implemented.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You need to enable "Return only best matching credentials"

**Comment by piegamesde** [comment]
Enabling the option does not resolve the issue. (IMO, this should work regardless of the option anyways.)

**Comment by droidmonkey** [comment]
No because we match the domain, not the path. Best matching (should) take the path into consideration.

**Comment by piegamesde** [comment]
> Best matching (should) take the path into consideration.

I agree. But I fear that best matching simply returns one entry instead of the whole list of matching items. Which would imply that the match sorting does not look at the full path, even though it should.

Maybe adding a special case for perfect matches to all respective methods would help?

**Comment by varjolintu** [comment]
I'll take a look at this. The matching definitely needs some tuning.

**Comment by varjolintu** [comment]
I just tested this using the following URL's: `https://discord.com/register` and `https://discord.com/login`. I created two entries with those URL's. When _Return only best matching credentials_ is disabled, both pages return both entries. When the option is enabled I only got the entry with the correct path.

So it seems to work as intended. Or have I missed something?

**Comment by droidmonkey** [comment]
Fixed for 2.6.2

**Comment by Ordiel** [comment]
This is not fixed, I am still facing the exact same issue as the one described on 2.7.6 and I **do** have the suggested option enabled

![image](https://github.com/keepassxreboot/keepassxc/assets/9622612/6302580f-7a1a-4be0-af23-7d04c83709c7)

**Comment by varjolintu** [comment]
@Ordiel What site are you using, and what URL's do you have in your entries?
