### ISSUE TITLE
KeeShare File Browse Dialogue closes after 20 seconds - macOS

### ISSUE THREAD

**Issue by islamadel** [keepassxreboot/keepassxc#4846]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When selecting the keeshare File in the Browse Dialogue, the window closes after 20 seconds. This is not enough time to select the required file.

## Steps to Reproduce
1. right click a group > edit group 
2. KeeShare > click the Browse icon near Path
3. While choosing the file, the window will close after 20 seconds.

## Expected Behavior
Window should remain open, until selection is done

## Actual Behavior
window closes after 20 seconds

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4 + 2.6.0-snapshot

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Mojave 10.14.6

**Comment by droidmonkey** [comment]
Fixed in 2.6.0

**Comment by islamadel** [comment]
Bug Still exists in 2.6.0 stable release. As soon as I click on Browse.. the windows closes after few seconds.

**Comment by droidmonkey** [comment]
Yah I noticed

**Comment by droidmonkey** [comment]
Duplicate of #5295
