### ISSUE TITLE
Icons missing after upgrade to 2.6.0

### ISSUE THREAD

**Issue by piramiday** [keepassxreboot/keepassxc#4963]
## Overview
on Linux Mint 19.3 MATE, after having updated KeePassXC to 2.6.0 as per the official Ubuntu PPA, the icons are garbled:

![Screenshot at 2020-07-07 14-07-25](https://user-images.githubusercontent.com/48775554/86843271-31e6fd00-c05b-11ea-9535-fc9cbf4ef451.png)

am I missing some new dependencies? is this normal? thanks.

## Context
```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-62-generic
```

**Comment by droidmonkey** [comment]
Those icons are incredibly broken

**Comment by okaestne** [comment]
I'm having the exactly same issue, Mint 19.3 (Cinnamon) as well. Changing icon theme doesn't help.

**Comment by john9527** [comment]
Same here....Mint 19.2 (Cinnamon)

**Comment by koelle25** [comment]
I am having the same issue. Linux Mint 19.3 (Cinnamon). Installed via ppa.

Interestingly also the theme choosing option is missing in the settings (was available under "User Interface" in the 2.6.0-beta1 release). Maybe this is related.

**Comment by droidmonkey** [comment]
Theme choice is now in the view menu

**Comment by piramiday** [comment]
several people seem to be experiencing this, so this could possibly occurr on any distro derived from Ubuntu 18.04.

@droidmonkey any ideas? fixes? workarounds? otherwise I'll downgrade because I have no idea what I'm clicking.

**Comment by droidmonkey** [comment]
Use appimage or snap distro

**Comment by koelle25** [comment]
I can confirm that the AppImage-Version is working fine.

**Comment by telans** [comment]
Assuming I have the same issue, it is not just related to Mint.

![Screenshot from 2020-07-08 13-16-29](https://user-images.githubusercontent.com/45819748/86862538-7f2ba300-c11d-11ea-9a77-401f7feb6162.png)

```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.7.6-gentoo

Enabled extensions:
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6
```

**Comment by droidmonkey** [comment]
@telans your issue looks completely different.

**Comment by LinuxOnTheDesktop** [comment]
I have the same problem on Mint 19.3 Cinnamon:

![image](https://user-images.githubusercontent.com/47056543/86872106-7d3cf200-c0d3-11ea-93c8-142e20ed3ceb.png)

I changed the KeePassXC theme setting from 'automatic' to 'dark' and to 'system native' but neither of those changes helped.

Still, the new look with this version of KeePassXC is very nice!

```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.6.13-050613-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

I will test on the newly released Mint 20 if I get a chance.

**Comment by stevenjhall** [comment]
Same problem here: Linux Mint 19.3 ppa
Snap version looks fine.

**Comment by iangozl** [comment]
I thought I was the only one. Damn. I installed it from the official ppa. I appreciate the theme change, but somebody forgot to put the icons.

![Screenshot from 2020-07-08 01-09-03](https://user-images.githubusercontent.com/17865341/86883880-57eeba80-c0b8-11ea-9b2d-4f2059e232d9.png)

`KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.4.0-40-generic`

**Comment by syphernl** [comment]
I see a lot of Mint users here. But I'm using Budgie 20.04 (fully up-to-date) and getting the very same issue after updating to 2.6.0.

**Comment by phoerious** [comment]
So it took Ubuntu only two years this time to create LTS issues for third-party apps? Nice.

I couldn't reproduce any of this on Ubuntu 20.04. Qt 5.9 is not an LTS release and will not get any updates except security backports by Canonical.

**Comment by phoerious** [comment]
BTW please make sure you have `libqt5svg5` installed.

**Comment by bvhoesel** [comment]
Same issue using Linux Mint Mate 19.3 with PPA. Library libqt5svg5 is installed. Added -dev lib also. But still most of the icons are missing. Error messages when startting from terminal:

 $ keepassxc
qt5ct: using qt5ct plugin
qt5ct: palette support is disabled
qt5ct: D-Bus global menu: no
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active

**Comment by phoerious** [comment]
The error means the image loaded into QPainter is empty, which points to a decoding issue or missing image plugin.

**Comment by JoeJoeTV** [comment]
I also have this issue, and I've tried a few things like different icon themes, different qt themes and I got nothing.

**Comment by droidmonkey** [comment]
Interestingly this only impacts the material icons used for menus, the default database icons are unaffected. I think this has something to do with when we are recoloring the SVG's on first use.

**Comment by phoerious** [comment]
I don't think it's the recolouring, it's the loading of SVGs somehow. The icons that do exist are the wrong ones that slip through from the system theme.

**Comment by phoerious** [comment]
The problem is indeed the SVG loading:

```
QImage img = icon.pixmap(128, 128).toImage().convertToFormat(QImage::Format_ARGB32_Premultiplied);
``
retursn QImage(null) for most icons.

**Comment by phoerious** [comment]
Probably caused by this bug: https://bugreports.qt.io/browse/QTBUG-63187

Some icons are loading, most are not. I cannot reproduce it on KDE, so maybe they have some magic workaround. I can reproduce it in a Mint VM, however. There doesn't seem to be a workaround except for switching from SVG to PNG.

**Comment by lagagain** [comment]
same issue. and the icon in the system tray is also missing.

![image](https://user-images.githubusercontent.com/26619182/86922784-b458e500-c15f-11ea-8a25-b38a5323868e.png)

**Comment by phoerious** [comment]
I'm on a loss here. It's clearly a Qt bug. Some icons do load, most don't. Unlike what I suspected before, the deciding factor is not whether the icon is PNG or SVG. It appears to be entirely random.

**Comment by phoerious** [comment]
I am starting to think that this is a Mint bug, not a Qt or Ubuntu bug. Since I couldn't reproduce it in my Kubuntu 20.04 VM, I plain Ubuntu 16.04, 18.04, and 19.10 live systems and none of them show this bug. This is Ubuntu 19.10 with KeePassXC installed from the PPA:

![image](https://user-images.githubusercontent.com/911270/86933259-a5137080-c13a-11ea-8bea-8ce4803a2721.png)

Is Mint using some sort of custom QIconEngine that might interfere with icon loading?

**Comment by LinuxOnTheDesktop** [comment]
@phoerious 

Thank you for investigating. However: someone above reports having the problem under Budgie. That distro is a version of Ubuntu and not of Mint.

**Comment by phoerious** [comment]
Budgie is using Budgie as its desktop environment. Neither plain Ubuntu (Unity or Gnome), nor Kubuntu have it.

**Comment by LinuxOnTheDesktop** [comment]
@phoerious

Perhaps I miss something. Here is how things seem to me. If various flavours of Mint (MATE, Cinnamon, perhaps others), but also Budgie, have the problem, then surely the problem does not consist solely in something to do with Mint. Perhaps Mint shares something - something problematic - with Budgie?

**Comment by phoerious** [comment]
Either the distributions have patched Qt somehow or the desktop environments are doing something funky.

**Comment by LinuxOnTheDesktop** [comment]
@phoerious

OK. So, if you determine what the funky behaviour is, and what is doing it, then it can get reported against the right project(s).

**Comment by phoerious** [comment]
I found it! The problem is actually qt5ct. If you unset `QT_QPA_PLATFORMTHEME` or set it to `gtk2`, it works. qt5ct is not used on Unity, Gnome, or KDE.

**Comment by droidmonkey** [comment]
A bug report should be filed against qt5ct

**Comment by phoerious** [comment]
Yeah, if only it weren't a Sourceforge project. Eww...

**Comment by bvhoesel** [comment]
Thanks for investigating so fast. Changing the environment variable does get the icons 'back'. But it also changes the fonts for me. So this is not the real solution for me.

**Comment by LinuxOnTheDesktop** [comment]
Datapoint: for me on Mint 19.3 Cinnamon, either of those two workarounds restores the icons (though also seemingly removes the dark theme and the option for the dark theme; my fonts did not seem to change).

**Comment by mlippert** [comment]
The toolbar icons are ok for me, but the system tray icon isn't. I'm running Linux Mint KDE 18.3 (so an older version).
Yes I will eventually upgrade (probably to Kubuntu 20.04) but for now it's a pain that after the upgrade I can't see the keepassxc icon in the system tray.
The keypassxc icon is between the red shutdown icon and the yellow knotes icon in this image, hovering will show the KeePassXC tooltip
![KeepassXC_2 6 0_systemtray_icon_LMKDE18 3](https://user-images.githubusercontent.com/2589356/86944657-0bd26300-c116-11ea-96f6-bc11772e3e44.png)

**Comment by droidmonkey** [comment]
Stay on topic please

**Comment by markkrj** [comment]
Can this be fixed in keepassxc packaging?

As a workaround I copied `/usr/share/applications/org.keepassxc.KeePassXC.desktop` into `~/.local/share/applications`, modified `Exec=keepassxc %f` to `Exec=env QT_QPA_PLATFORMTHEME= keepassxc %f` and restarted the cinnamon shell and it is working. Also modified Exec line in automatic startup file (`.config/autostart/org.keepassxc.KeePassXC.desktop`) to `Exec=env QT_QPA_PLATFORMTHEME= /usr/bin/keepassxc`.

Here's an script for this workaround:
```
cp /usr/share/applications/org.keepassxc.KeePassXC.desktop ~/.local/share/applications/
sed 's;^Exec.*;Exec=env QT_QPA_PLATFORMTHEME= keepassxc %f;' -i ~/.local/share/applications/org.keepassxc.KeePassXC.desktop
[ -f .config/autostart/org.keepassxc.KeePassXC.desktop ] && sed 's;^Exec.*;Exec=env QT_QPA_PLATFORMTHEME= /usr/bin/keepassxc;' -i .config/autostart/org.keepassxc.KeePassXC.desktop
```
After changing the files, hit `alt+f2`, type `r` and hit `enter`

**Comment by mishley** [comment]
Thanks @markkrj your workaround worked perfectly. I had to re-set the theme to Dark from the View > Theme menu inside the app once I restarted Cinnamon, and now the icons are visible again!

**Comment by phoerious** [comment]
You should probably set it to gtk2, so it picks up your GTK font settings at least.

**Comment by LinuxOnTheDesktop** [comment]
Here is a happy datum: I have tested the PPA version on Linux Mint 20 Cinnamon - without any hacks (but in a VM) - and the icons work. Mint 20 is based upon Ubuntu 20.04.

**Comment by ruanmed** [comment]
Some _Settings page_'s icons (and the tray icon) were missing in Linux Mint 19.3 XFCE, and I did @markkrj 's workaround and they started working.

Before:

![image](https://user-images.githubusercontent.com/4930746/86964192-0ab42c80-c13c-11ea-8a9b-9b9f4cfc65aa.png)

After:

![image](https://user-images.githubusercontent.com/4930746/86964047-d9d3f780-c13b-11ea-8ba5-3aaf786af1be.png)

**Comment by droidmonkey** [comment]
Time for everyone to update to Mint 20...

**Comment by LinuxOnTheDesktop** [comment]
'Time for everyone to update to Mint 20': perhaps not. Here's why. Mint 20 came out only last month. Seasoned Mint users recommend that people wait at least a month or even perhaps until the first 'point' release. For, there tend to bugs (albeit some of them inherited from Ubuntu). I myself am having troubles running Mint 20 in a Virtual Machine (though possibly that is the fault of VirtualBox).

Still, I can confirm that markkrj's helpful script does do the job on Mint 19. I note also that amending that script to mention 'gtk2' made the icon problems re-occur.

**Comment by phoerious** [comment]
qt5ct bug report: https://sourceforge.net/p/qt5ct/tickets/80/

**Comment by phoerious** [comment]
Fixed in the upcoming 2.6.1 release.

**Comment by Chugajstyr** [comment]
> Here is a happy datum: I have tested the PPA version on Linux Mint 20 Cinnamon - without any hacks (but in a VM) - and the icons work. Mint 20 is based upon Ubuntu 20.04.

Doesn't work for Mint 20 Mate - upgraded today, icons still missing.

**Comment by LinuxOnTheDesktop** [comment]
It does not work for me on real - as against virtual - Mint 20 Cinnamon. So I tried testing the virtual version again; and, not for the first time recently, VirtualBox refused to boot. Still, on real Mint 20 Cinnamon, I find that the script hack, posted above, works.

**Comment by bvhoesel** [comment]
Just for reference: not only KeepassXC suffers from this 'issue', also the latest version of QOwnNotes shows the exact same effects (On Mint Mate 19.3).
So it seems to be a broader context issue. On an other Mint Mate 19.3 machine there is no issue. That machine has hardly extra software installed. Any body knows how to 'clean' the qt5 environment without 'breaking' the machine?

**Comment by phoerious** [comment]
It's a qt5ct issue. Please read the rest of the thread.

**Comment by marrowsuck** [comment]
Seems to be fixed n qt5ct with commit [r575]:
https://sourceforge.net/p/qt5ct/code/575/

**Comment by phoerious** [comment]
Yes, I tested the patch and it works. But it will take time until the patch arrives in downstream distributions. Some LTS distributions might never get it.

**Comment by LinuxOnTheDesktop** [comment]
I wonder what to do about phoerious's point about the patch landing slowly or not at all on some distros. I wonder this especially since I find that the workaround posted above stops working after a while (after a reboot) and that something - perhaps the workaround - prevents the KeePassXC tray icon from showing on my Mint 20 Cinnamon computers. I note also that the patch is to a C++ file and so would require compilation - it's not a mere matter of changing some lines in a file.

**Comment by droidmonkey** [comment]
If the env var is not persistent than that would mean you are not applying it correctly. The env var should ALWAYS work if you are explicitly launching KeePassXC with it. Additionally, we added a code fix on our side for 2.6.1 that corrects this issue.

**Comment by LinuxOnTheDesktop** [comment]
@droidmonkey 

I was using the script provided by @markkrj. I have now undone what it did and I will await 2.6.1. Thanks. Unfortunately I still see only a blank space - of varying sizes - where the tray icon should be, even after removing just about all traces of KeePassXC and reinstalling it, but that's probably a bloomin' Cinnamon problem.

**Comment by jensrutschmann** [comment]
@phoerious Sorry if this is slightly OT, but I saw you mentioning in the [qt5ct bug report](https://sourceforge.net/p/qt5ct/tickets/80/#2ff5):
> which forces Qt to fall back to the system icon theme resulting in some system icons being shown

I think I'm running into a similar issue under KDE on Arch: When using the colorful tray icon, the locked icon is taken from the system theme, it's this one: https://github.com/KDE/breeze-icons/blob/master/icons/status/22/keepassxc-locked.svg
The unlocked icon is taken from KeepassXC (it's the green app icon as expected) and also all other icons in the app seem to work as expected, it's only this one.

I don't have qt5ct installed.

Is this related to the same problem or should I create a new issue?

**Comment by droidmonkey** [comment]
There is no way we are pulling from the system icons for tray icon. We only look in the compiled in resources for those icons.

**Comment by jensrutschmann** [comment]
@droidmonkey I logged out, on a VT deleted ~/.cache, logged back in -> same problem. Are there any other locations where the icon might be cached?

**Comment by droidmonkey** [comment]
Launch KeePassXC with `QT_QPA_PLATFORMTHEME= keepassxc`. This will be addressed in 2.6.1.

**Comment by jensrutschmann** [comment]
@droidmonkey Launching with `QT_QPA_PLATFORMTHEME= keepassxc` doesn't change anything.

I debugged this a bit further:
* It also happens with a clean user account, (deleted all (dot) files in home) so I don't think it's related to (user-level) caching.
* It seems to be related to the icon file names:
    * The color icons in KeepassXC are:
        * `share/icons/application/scalable/apps/keepassxc.svg`
        * `share/icons/application/scalable/apps/keepassxc-locked.svg`
    * The breeze theme contains:
        * `/usr/share/icons/breeze/status/22/keepassxc-unlocked.svg`
        * `/usr/share/icons/breeze/status/22/keepassxc-locked.svg`
* If I rename `/usr/share/icons/breeze/status/22/keepassxc-locked.svg` to something else, the locked icon is taken from KeepassXC and not the breeze theme anymore.
* If I rename the breeze file `/usr/share/icons/breeze/status/22/keepassxc-unlocked.svg` to `/usr/share/icons/breeze/status/22/keepassxc.svg` (so it matches the unlocked icon filename from within KeepassXC) then suddenly the unlocked icon is also taken from Breeze rather than the bundled icon.

Let me know if you think it will still be fixed by 2.6.1 or if I should create a separate issue for this.

**Comment by jensrutschmann** [comment]
The same behavior applies to the app icon as used in KDE task bar or the "start menu":
Once I had renamed the breeze file `/usr/share/icons/breeze/status/22/keepassxc-unlocked.svg` to `/usr/share/icons/breeze/status/22/keepassxc.svg` the app icon was no longer the green icon but the one from the breeze theme.
And just to confirm: this happens with 2.6.0 so some code is definitely still loading system theme icons.

**Comment by thierrybo** [comment]
I can confirm using "env QT_QPA_PLATFORMTHEME= keepassxc" restore icons, although i loose gtk theme. I have no DE, only Openbox with qt5ct.

```
KeePassXC - Version 2.6.0
Révision : 0765954

Qt 5.14.2
Le mode débogage est désactivé.

Système d’exploitation : Devuan GNU/Linux 4 (chimaera/ceres)
Architecture de l’unité centrale : x86_64
Noyau : linux 5.7.0-1-amd64

Extensions activées :
- Saisie automatique
- Intégration aux navigateurs
- Agent SSH
- KeeShare (partage non signé uniquement)
- YubiKey
- Intégration au Secret Service

Bibliothèques cryptographiques :
 libgcrypt 1.8.5
```

**Comment by droidmonkey** [comment]
Locking this since the solution is already merged in 2.6.1
