### ISSUE TITLE
Yubikey hardware key no longer detected under 2.6.0

### ISSUE THREAD

**Issue by rse12345** [keepassxreboot/keepassxc#4987]
just updated to KeepassXC2.6.0 on windows 10 pro 2004 - trying to open database with hardware key (yubikey standard 2.4.2 firmware). Yubikey is not detected. 

The yubikey is detected by the yubikey personalisation tool on my computer and appears to be functioning normally.

**Comment by kaikobarg** [comment]
hey you, i just installed V 2.6.0 and had exactly the same problem you mentioned above ! the field "hardware token" was blank. pressing the button "reload" next to the field did not help either. 
the only way to get access to my keepass-database again, was to deinstall Version 2.6.0 and reinstall Version 2.4.2.

**Comment by droidmonkey** [comment]
Do you both have a yubikey standard?

**Comment by kaikobarg** [comment]
I use a Yubikey 5 Neo via USB-Port

**Comment by SirJson** [comment]
I can report the same issue, both of my YubiKeys are not detected by version 2.6.0. I checked if other applications are having the same issue but they continue working just like they did yesterday. The YubiKey Manager is also detecting both correctly.

The keys I'm using are YubiKey 5 NFC USB-A running Firmware 5.2.4.

As a sanity check I reinstalled the previous KeePassXC version 2.5.4 and this version still detects my YubiKeys and can open my database without any problems.

**Comment by droidmonkey** [comment]
@SirJson what OS and distribution format are you using?

**Comment by droidmonkey** [comment]
For everyone, in the YubiKey Personalization Tool, does your YubiKey show a serial number:

![image](https://user-images.githubusercontent.com/2809491/87034114-5525bf80-c1b5-11ea-9774-34040028e2c4.png)

The new implementation tracks your key by serial number (that is what allows for multiple keys), but if the firmware doesn't provide a serial number than it won't work at all.

Unfortunately, Yubico firmware varies wildly between keys because of their decision to not allow firmware flashing.

**Comment by max-stockhausen** [comment]
Because I have the same problem, here is a screenshot of my personalisation tool. It shows a serial number for my YubiKey 5 NFC
![yubikey_pers-tool](https://user-images.githubusercontent.com/44135545/87038900-aaca8e00-c1ee-11ea-8ba4-71a33589c1c7.jpg)

**Comment by igaritano** [comment]
I have a similar problem on Debian 10.

KeePassXC 2.6.0 does not recognize the Yubikey 4 while running.
I have to close the app and open it again while Yubikey is connected.

I checked again with KeePassXC 2.5.4 and works perfectly. I can disconnect/reconnect the YubiKey and KeePassXC recognizes it without any issue.

**Comment by droidmonkey** [comment]
We repoll for the key every time we want to use it, which is completely different from 2.5.4 that held onto a USB instance for the duration of the program. If anything it should always work in 2.6.0 and certainly I tested that case in ALL operating systems.

**Comment by teedog** [comment]
Same issue here with a YubiKey 5 NFC. Running KPXC 2.6.0 on windows 10.0.17763. The key is running on firmware version 5.2.4, serial number dec is 10655617. SSH key authentication with ssh-agent works as always. When hitting _Hardware Key: Refresh_ inside KPXC, the key blinks green and the combo box flickers but the key is not showing up.

**Comment by rse12345** [comment]
thanks for the reply - I can confirm that my yuibkey personalisation tool shows that I do have a serial number for my yuibkey standard

**Comment by trumpet205** [comment]
I am having the same problem too on Windows 10 Version 2004 (64-bit).

Tried both YubiKey 5 NFC I had: firmware version 5.1.2 (9714699) and version 5.2.4 (11490086) 

2.6.0 cannot detect them both (keys lit up when pressed refresh but nothing more). Right now I reverted back to 2.5.4.

**Comment by 1overdrive** [comment]
Same issue. All 3 of my keys (all firmware 5.2.4) report their serial# correctly in ykey personalization tool, ykman, and various gpg agents. My key does light up when trying to refresh key detection in 2.6.0, but no key is reported by the program

**Comment by droidmonkey** [comment]
Ok so when I get my Yubikey 5 NFC I'll fix this issue.

**Comment by iamjakko** [comment]
same issue with one of an older yubikey with firmware version 4.1.1 on my linux mint 20. i have reverted back to an older version of keepassxc.

**Comment by cheeseandcereal** [comment]
> Unfortunately, Yubico firmware varies wildly between keys because of their decision to not allow firmware flashing. The only keys I have are YubiKey Neo (original), YubiKey 4, and OnlyKey. I am ordering a YubiKey 5 NFC now.

@droidmonkey 
I've got a YubiKey Neo (original) on firmware 3.4.9 and a YubiKey 4 Nano on firmware 4.3.5, and neither of them work for me. I have tested both of those on Ubuntu 20.04 with the official PPA as well as on MacOS with the keepassxc cask and no combination works, so it's definitely not just the YubiKey 5. Both of them show a serial, and it might be worth noting that both of them also have all 3 interfaces (OTP, FIDO, and CCID) enabled.

I'm happy to help debug if there's anything I can do.

**Comment by droidmonkey** [comment]
My guess is that the failure is on line 3/4 of this code block:

```
for (int slot = 1; slot <= 2; ++slot) {
    auto config = (i == 1 ? CONFIG1_VALID : CONFIG2_VALID);
    if (!(ykds_touch_level(st) & config)) {
        // Slot is not configured
        continue;
    }
    // Don't actually challenge a YubiKey Neo or below, they always require button press
    // if it is enabled for the slot resulting in failed detection
    if (pid <= NEO_OTP_U2F_CCID_PID) {
        auto display = tr("%1 [%2] Configured Slot - %3")
                           .arg(vender, QString::number(serial), QString::number(slot));
        ykSlots.append({slot, display});
    } else if (performTestChallenge(yk_key, slot, &wouldBlock)) {
        auto display = tr("%1 [%2] Challenge Response - Slot %3 - %4")
                           .arg(vender,
                                QString::number(serial),
                                QString::number(slot),
                                wouldBlock ? tr("Press") : tr("Passive"));
        ykSlots.append({slot, display});
    }
}
```

**Comment by cheeseandcereal** [comment]
> ```
> for (int slot = 1; slot <= 2; ++slot) {
>     auto config = (i == 1 ? CONFIG1_VALID : CONFIG2_VALID);
>     if (!(ykds_touch_level(st) & config)) {
> ```

Shouldn't line 2 there be `slot ==1`, not `i==1`?

**Comment by cheeseandcereal** [comment]
The problem is with that codeblock, but it's because you typo'd `i == 1` which is the number of yubikey instead of `slot == 1`.

This makes it so if you only have one yubikey plugged in, then it will only check slot 1, causing this bug.

**Comment by cheeseandcereal** [comment]
@droidmonkey 
The problem is with that codeblock, but it's because you typo'd `i == 1` which is the number of yubikey instead of `slot == 1`.

This makes it so if you only have one yubikey plugged in, then it will only check slot 1, causing this bug.

I have my 2 yubikeys set up with _only_ slot 2, and confirmed this by seeing one of the keys detect properly when there are 2 keys plugged in at the same time (since the second key will be i = 2, where my slot is).

I submitted a PR to fix this

**Comment by droidmonkey** [comment]
Holy cow!!!

**Comment by droidmonkey** [comment]
Fixed in #5004

**Comment by SirJson** [comment]
I've just built the release/2.6.1 branch on Windows 10 and can confirm that my Keys got detected again and I was able to unlock my db with it. Good job on fixing the problem so quickly! I was worried I would be stuck on 2.5 for quite some time 😄

**Comment by teedog** [comment]
Is there maybe a build from a CI system that we can test? The explanation of @cheeseandcereal absolutely makes sense. Forgot to mention: My YubiKey also is configured on slot 2.

**Comment by rse12345** [comment]
great job thanks

**Comment by droidmonkey** [comment]
I merged v2.6.1 branch into develop, you can test the YubiKey fixes from the latest snapshot: https://snapshot.keepassxc.org/latest

**Comment by HarrPerson** [comment]
Great. Had the same problem. Snapshot works for me under Linux. 👍Tested the AppImage Version from 2020-07-13 03:22

**Comment by teedog** [comment]
Works on Windows 10, YK 5 NFC, Slot 2. Thanks for that fast fix!

**Comment by rupi-lol** [comment]
Cannot reproduce - reading this thread I was fearfull when I realized Debian testing upgraded to 2.6.0, but I have no trouble with recognition of my yubikey:
* YubiKey 5 NFC (Firmware version 5.1.2) - Slot 2 used for challenge response
* keepassxc version 2.6.0+dfsg.1-1

I browsed the only patch used by debian (https://sources.debian.org/src/keepassxc/2.6.0+dfsg.1-1/debian/patches/series/) only briefly but as far as I read it doesn't touch handling of yubikeys.

**Comment by SirJson** [comment]
They would need commit 4f1d894 as a patch. Looking at the changeset it should be easy to include into debian. Have you tried building the latest develop branch yourself? It includes this commit and building [KeePassXC is pretty well documented](https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux).

**Comment by felker** [comment]
Searched the Issues and couldn't find if this was already reported somewhere / related to this issue, but since installing v2.6.0, my Hardware Key is never remembered (YubiKey Slot 2- Passive). I have to manually select it from the dropdown menu every time. 

Even if I close the database and immediately try to open it, there is a short latency where it shows "Detecting hardware keys..." before I am forced to manually select it.

**Comment by droidmonkey** [comment]
Have you tried a snapshot build to confirm it was fixed?

**Comment by felker** [comment]
Confirmed that this minor issue still occurs on the snapshot. Should I open a fresh issue?

**Comment by droidmonkey** [comment]
Sure, but you should attempt to isolate why the issue is occurring because it certainly doesn't occur in my testing or for anyone else in this issue thread (which specifically affects slot 2). Do you have the setting "Remember database key files and security dongles" enabled?

**Comment by felker** [comment]
Yes, that option is enabled. I am on macOS Catalina, and I use a YubiKey 5C Nano (firmware 5.1.2). 

![keepassxc-report-2_6_0](https://user-images.githubusercontent.com/1410981/88005013-e9552800-cacd-11ea-90bb-4b9d74c0402a.gif)

**Comment by felker** [comment]
KeePassXC started remembering my database's Hardware Key again today (didnt change anything since last night), so it seems this behavior is somewhat unpredictable.

**Comment by x86dev** [comment]
Can confirm that the latest 2.6 snapshot also fixes the issue for me. Thanks for fixing!

**Comment by srd424** [comment]
For anyone else arriving here .. even with 2.6.1, I had to disable "remember security keys", close, restart, renable the option, close, restart .. and now it remembers!

**Comment by OdinVex** [comment]
Coming from 2.4.3, I can't use any v 2.6+. Attempted 2.6.0 and 2.6.1 again and neither detects my YubiKey 5 Nano. It's a real key, serial is there as well. 2.6.0 showed random serials on each Refresh (noted as fixed in 2.6.1?) but 2.6.1 just shows "15" for the serial and is incorrect. Refreshing still shows 15. Falling back to 2.4.3.

**Comment by cheeseandcereal** [comment]
@OdinVex That sounds like a different issue than what this particular issue was tracking. Do you have any more information? Maybe create a new github issue with some additional information if possible.

**Comment by OdinVex** [comment]
@cheeseandcereal Issue matches most of the other things reported in this one. Second one, even. Not exactly sure what information I could provide. YubiKey 5C Nano, worked in 2.4.3, doesn't work 2.6.0+. Using Ubuntu PPA. Refreshing shows the YubiKey but no longer works, thinks it has a serial number of 15. In 2.6.0 it was a random serial due to the typo in code.

**Comment by cheeseandcereal** [comment]
2.6.0 didn't cause the serial number to change at all. The code typo simply made it so that if you had a yubikey where the _only_ slot configured was slot 2, then it wouldn't show up in 2.6.0 (and was since fixed in 2.6.1).

> Refreshing shows the YubiKey but no longer works

What do you mean by 'no longer works'? Are you getting an actual error message or screenshot you can share? It's hard to diagnose a problem when the description of the issue is it 'no longer works'. What about v2.5? You said you came from 2.4, but was this a bug introduced in one of the 2.5.X version, or 2.6?

**Comment by OdinVex** [comment]
I know it didn't change the serial number of the actual hardware. According to YubiKey, serials cannot be changed. Tin-foil hat doubts that but anyway...
I have not tried any 2.5.* builds. Build 2.4.3 is the only non-2.6.* build I can try at the moment. Build 2.6.0 showed random serials for the same YubiKey on each Refresh. As mentioned earlier build 2.6.1 thinks the serial number is '15' even if Refreshed. Not exactly sure how I can clarify any further. Cannot open the db, KeePassXC being unable to find the YubiKey (any 2.6.* build...).

**Comment by droidmonkey** [comment]
You need to provide operating system, manner of install (apt, ppa, appimage, snap), and in this case what version of libykpers you have installed.

**Comment by OdinVex** [comment]
Not sure why any of that matters considering _2.4.3 works_ and _2.6.* doesn't_ but whatever, Ubuntu-_like_, KeePassXC's ppa, libkypers 1.20.0-2.

**Comment by droidmonkey** [comment]
You mention it shows a serial number,  which means it is at least detecting the key. Can you not unlock your database with the key?

**Comment by OdinVex** [comment]
> You mention it shows a serial number, which means it is at least detecting the key. Are you able to unlock your database with the key even though the serial number is wrong? Can you try using the appimage to rule out library interference?

It of course shows the key in the selection but the serial is always wrong. The AppImage showed a random serial but it failed to open the database because no device had that serial number. Refreshed, serial always shows as "1".

**Comment by droidmonkey** [comment]
I think your yubikey is non-functional.

**Comment by OdinVex** [comment]
Got it working. I had disabled serial-api-visible, serial-btn-visible, serial-usb-visible long ago. I suspected they were problematic and re-enabled them but forgot to update the configuration. Still, KeePassXC may need a work-around or an option to detect this issue and maybe alert people.

**Comment by Germano0** [comment]
I eject myself from this ticket, if there are any other problems please ping me (I am the Fedora co-maintainer)
Thank you

**Comment by cwross** [comment]
For what it's worth, I wanted to report that on 2.6.2 under Void Linux (and installed from the Void repo), the Yubikey is only detected if inserted prior to launching KeePassXC. If the key is inserted after launching the program, it will not be found.

Using the 2.6.2 AppImage works as expected.

**Comment by droidmonkey** [comment]
Then that would be a problem with the void Linux provided yubikey libraries since appimage supplies its own.

**Comment by phoerious** [comment]
Even when you hit refresh?

**Comment by cwross** [comment]
> Even when you hit refresh?

Correct; the refresh button does nothing.

**Comment by robbjas** [comment]
Hello, YubiKey 5 NFC is not detected when trying to add it via Database -> Security -> Add additional protection. When I click "Refresh" nothing happens. When I click "Refresh" button and then put my finger onto key window pops out: "Could not find any hardware keys!". When I click "Cancel" then touch the key it is treated same as clicking "Cancel" button under "Refresh" button (very interesting). 

YubiKey slot 2 is properly configured for HMAC-SHA1 challenge-response with YubiKey Personalization Tool. 

What is important this is **snap** version. AppImage version works fine.

Debug info:
KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-60-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Add raw USB permissions... https://keepassxc.org/docs/#faq-appsnap-yubikey

**Comment by locksec** [comment]
I am still having this issue. Any ideas?

Yubikey 5 NFC
KeePassXC 2.6.6
Windows 10 Pro (20H2)

`"No hardware keys detected"`

**Comment by droidmonkey** [comment]
It appears that the yubikey 5 nfc is not detected by yubikey's own library...

**Comment by locksec** [comment]
The Yubikey is working in Firefox and it all appears to be ok in Yubikey Manager.

**Comment by droidmonkey** [comment]
That doesn't mean anything, we use a specific library from yubikey that these other things don't use, it would seem. Can you extract the vid/pid of the device? We will have to manually enter that in.

**Comment by locksec** [comment]
VID_1050
PID_0407

**Comment by OdinVex** [comment]
Make sure you haven't told the YubiKey to hide its serial number. I had a problem with KeePassXC giving me random IDs and not working.

**Comment by droidmonkey** [comment]
> VID_1050 PID_0407

That is the same PID as the Yubikey 4 OTP/U2F/CCID which is included in the search criteria. Very strange that it wouldn't work.

https://github.com/Yubico/yubikey-personalization/blob/97448fbdec9fc0dd1bebb044917b79a10eb21389/ykcore/ykdef.h#L292

https://github.com/Yubico/yubikey-personalization/blob/97448fbdec9fc0dd1bebb044917b79a10eb21389/ykcore/ykcore.c#L101-L104

**Comment by droidmonkey** [comment]
I just plugged in my Yubikey 5 NFC and it worked fine. Make sure at least one of the slots is configured for challenge-response.

![image](https://user-images.githubusercontent.com/2809491/139741914-32d84399-5152-4f00-b63f-f9198fd2bc4e.png)

![image](https://user-images.githubusercontent.com/2809491/139741976-7101f322-bec5-4f44-bac2-1d9a644d93d1.png)

![image](https://user-images.githubusercontent.com/2809491/139742059-6adaf15b-4e36-43bc-ad52-e303c4f1ed5d.png)

**Comment by locksec** [comment]
> Make sure at least one of the slots is configured for challenge-response.

That worked, I didn't realize the slot wasn't configured for challenge-response. Thanks for your help!

**Comment by stickynet** [comment]
My Yubikey 5 NFC (firmware 5.1.2; no serial number) works for KeepassXC 2.5.4 but not in 2.6.2 or 2.7.
I can select the key but get an error
 - existing Database: ... could not find hardware key with serial number xxxx ...
 - new Database: Selected hardware key slot does not support challange response!

Do i need to buy a new key xD ?

**Comment by Stev101n** [comment]
> Make sure you haven't told the YubiKey to hide its serial number. I had a problem with KeePassXC giving me random IDs and not working.

Thanks, that solved my problem :)
