### ISSUE TITLE
`keepassxc --version` activates KeePassXC window

### ISSUE THREAD

**Issue by runiq** [keepassxreboot/keepassxc#5194]
## Expected Behavior

Prints version, doesn't show main window

## Actual Behavior

Prints version, shows main window

## Context

I have these options active:

- single instance only
- minimize instead of exiting
- hide window when minimized

KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Fedora 32 (Thirty Two)
CPU-Architektur: x86_64
Kernel: linux 5.7.10-201.fc32.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Fixed in #5452

**Comment by quelbs** [comment]
For me this bug still exists. At least if KeePass is running in background, the window gets activated when executing `keepass --version`.

**Comment by runiq** [comment]
Yes, exactly. It's the same for me I'm afraid. v2.6.3 on Arch.
