### ISSUE TITLE
Can't move entries or groups on OSX

### ISSUE THREAD

**Issue by vandreykiv** [keepassxreboot/keepassxc#5597]
## Overview
Yesterday I do a little bit clean up of my database and created few new groups. Today I noticed that I can't move groups or entries between groups. When I take entry and try to move it somewhere nothing happens.

## Steps to Reproduce
1. Create a new entry
2. Hold a left mouse button and try to move to a new group
3. Nothing happens 

## Expected Behavior
1. Create a new entry
2. Hold a left mouse button and try to move to a new group
3. Entry moved to the new group 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15.7

**Comment by phoerious** [comment]
I cannot reproduce this bug.

**Comment by vandreykiv** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/598576/97061765-e8a8b380-154c-11eb-9a53-74e55ed366df.gif)
Here is how it works on my laptop. Have no idea what happened. Also rebooted the machine but without success

**Comment by phoerious** [comment]
Is your GIF incomplete or are you already unable to create a new database? I cannot reproduce any of that.

**Comment by vandreykiv** [comment]
I can create a new database and created it but the issue still here. Nevermind. I reinstalled the application and it started working as expected.

**Comment by cvachta** [comment]
I have same problem. MacOS Catalina 10.15.7.

**Comment by vandreykiv** [comment]
Removing application, leftovers and configs and reinstall solved this
problem for me.

**Comment by steffakasid** [comment]
@vandreykiv what did you delete exactly?

**Comment by vandreykiv** [comment]
@steffakasid I removed `keepassxc.ini` but not sure that it helped as I do uninstall/reinstall during that and somehow issue was fixed.

**Comment by steffakasid** [comment]
@vandreykiv thx a lot. I tried it alread but didn't solve it for me :(

**Comment by droidmonkey** [comment]
This is a qt bug and any workaround is temporary at best.

**Comment by kopolito** [comment]
Removing application, and `keepassxc.ini` and reinstall solved this
problem for me too.

**Comment by JDaoMothership** [comment]
I had this problem today, and I solved it just by closing/reopening the app. 🤷‍♂️

**Comment by dhavalwd** [comment]
Removing the app and reinstalling it did the trick for me.
