### ISSUE TITLE
[2.6.3] Try Icon sometimes not appear if KeePassXC automatically started with system.

### ISSUE THREAD

**Issue by MartinX3** [keepassxreboot/keepassxc#5943]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the Option "Automatically startup with system"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A nice try icon

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

No try icon
## Context
[NOTE]: # ( Give us any additional information you may have. )
If I quite the app and start it manually, the tray icon appears.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: EndeavourOS
CPU-Architektur: x86_64
Kernel: linux 5.10.7-zen1-1-zen

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.8.7
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux / EndeavourOS
Desktop Env: XFCE 4.16
Windowing System: X11

**Comment by droidmonkey** [comment]
Uncheck the startup setting, press ok,  check the startup setting, press ok. That should fix it.

**Comment by MartinX3** [comment]
Sadly that didn't fix it for me.
Also the autostart entry in xfce still looks the same like before with the trigger "on login".
Should there be any difference now?

**Comment by bbx0** [comment]
Same here but with GNOME on Arch Linux. Looks like the parameter `X-GNOME-Autostart-Delay` is not supported by upstream GNOME [gsm-autostart-app.h](https://gitlab.gnome.org/GNOME/gnome-session/-/blob/master/gnome-session/gsm-autostart-app.h) and Ubuntu uses a patch to enable it [support_autostart_delay.patch](https://salsa.debian.org/gnome-team/gnome-session/-/blob/ubuntu/master/debian/patches/ubuntu/support_autostart_delay.patch).

Easiest way to mimic the workaround is to add a `sleep` to the `Exec` in `~/.config/autostart/org.keepassxc.KeePassXC.desktop`.
```
Exec=sh -c "sleep 2 && exec /usr/bin/keepassxc"
```

**Comment by MartinX3** [comment]
Ah, then it's a GNOME specific change.
I read that KDE, XFCE and LXDE doesn't support it.
Probably LXQT as well not.

**Comment by MartinX3** [comment]
Is there some bug deep inside KeePassXC since other apps without the need of a delay doesn't share this behavior @droidmonkey ?

**Comment by MartinX3** [comment]
I created a bug issue ticket for XFCE in the hope they add a "delay" feature for such workarounds.
https://gitlab.xfce.org/xfce/xfce4-session/-/issues/96

**Comment by droidmonkey** [comment]
There is a qt bug registered for this bad behavior

**Comment by MartinX3** [comment]
Do you have the link to this bug report?
Then we have it documented here and I can subscribe to it.

**Comment by droidmonkey** [comment]
I don't know it and can't find it. It's not our bug to fix.

**Comment by MartinX3** [comment]
But the lib you use and if it's fixed you can remove the workaround. ^^

**Comment by droidmonkey** [comment]
My mistake, it was a Gnome bug I was thinking of: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/75

**Comment by MartinX3** [comment]
Ah, thank you for the clarification :)
Hmm, I wonder why that happens only with KeePassXC in XFCE then.

**Comment by droidmonkey** [comment]
I added a workaround for this issue in my latest PR ^^

**Comment by MartinX3** [comment]
Aweseome, I can't wait to test it with the next arch update <3

**Comment by AJJLagerweij** [comment]
Thanks for the update in 2.6.4 it fixed the issues, however it required me to remove the tray icon and autostart options, save the settings and then enable both again to work properly. Is this expected behaviour?

**Comment by phoerious** [comment]
No, it should work without any of that.
