### ISSUE TITLE
Cannot save to Dropbox (Windows 10 1703 64-bit)

### ISSUE THREAD

**Issue by wrmbaron** [keepassxreboot/keepassxc#604]
When saving to any folder in my Dropbox using KeepassXC 2.1.4 on Windows 10 1703 64-bit, an error dialog pops up:
---------------------------
Error
---------------------------
Writing the database failed.

Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

---------------------------
OK   
---------------------------

My display language is German and I set the program language to English, so I guess there is another minor bug there. The message means, that the file cannot be accessed, because it is being used by another process.

Saving in any ordinary directory or a synced MEGAsync directory works without any problem. KeepassX has no problem cooperating with Dropbox (though I prefer to use KeepassXC!).

## Expected Behavior
The file should just be saved when I press Ctrl+S when the file is changed.

## Current Behavior
The above mentioned dialog appears. A file with the new content is saved in the same directory with ".q" and the process ID of the keepassxc executable appended.

## Possible Solution
Only a non acceptable workaround: rename the .q<id> file to the file you originally wanted to save. Then, you can use KeepassX for the moment for regular stuff and use KeepassXC only, when you have to merge databases or do other stuff, that only KeepassXC can do)

## Steps to Reproduce (for bugs)
1. Open a .kdbx file in your Dropbox
2. make a change, e.g. append character "a" to the note of "General/Sample Entry"
3. Press Ctrl+S or close KeepassXC and press "Yes"

## Context
Trying to apply changes to the database, the bug disrupts my everyday work.

## Your Environment
* KeePassXC 2.1.4/Revision: cb283bb95ae559d044415f426f841c27bff383f0
* Qt version (e.g. Qt 5.8): 
* Compiler (looks like gcc, it's the official download, so you should know best): 
* Operating System Windows 10 1703 64-bit
* Dropbox client 26.4.24

**Comment by droidmonkey** [comment]
I see this error in Google drive when its trying to sync the file i am saving to. Is your database file exceptionally large? You may also see this if there is a lockfile that is "stuck" in place.

**Comment by ejensler** [comment]
I recently switched from Keepass to KeepassXC for some of the additional features, but immediately got bitten by this same bug trying to use Dropbox to sync with my phone.

**Comment by droidmonkey** [comment]
I'll install Dropbox and do some testing. Thanks for the reports. @ejensler are you using Windows 10 as well?

**Comment by martinufo** [comment]
I have the same problem (Windows 10 / KeePassXC 2.2.0). If I pause syncing in Dropbox settings, I can save the database without error.

**Comment by Antauri** [comment]
Any ETA on this? Need help? (I'm experienced in Qt, what should I look into?) I just installed it and use Dropbox (to OneDrive/GDrive sync via Zapier) and this is pretty annoying (yet the XC is a muc more nicer KeepassX).

**Comment by coldloops** [comment]
same issue on windows 7 with the latest 2.2.0, db file is 10kb, not sure what you mean by the lock file being stuck be there was no lock file before opening the db.
also this is not a problem on linux.

**Comment by AbisachBerlin** [comment]
I have the same problem with Windows 10 (KeepassXC 2.2.0) using Dropbox to sync. But in Linux (Solus) and in Android, it works perfectly.

**Comment by droidmonkey** [comment]
I gave this a couple tries on my computer using dropbox (Win10). I could not reliably cause the saving of the database to fail. I turned on "autosave after every change" which trigged it a handful of times after making many back-to-back edits.

The only thing I think that will fix this is to attempt to save again after a set delay (perhaps even try a couple of times with progressively larger delays).

Any additional information you guys can provide would be very helpful.

**Comment by jeroen7s** [comment]
same issue here

**Comment by andschwa** [comment]
Same, but with Google Drive. Exiting Drive completely lets me save.

**Comment by Sucesso** [comment]
Same problem here.

> andschwa said: Exiting Drive completely lets me save.

Yay, this worked. Easy workaround.

**Comment by felixkopf** [comment]
Same issue here.

I figured out, that when I click "Save" or press CTRL+S two times quickly in a row, it works.
The first attempt fails with the error message and a new .kdbx.'something'-File is created in my Dropbox.

**Comment by NetWormKido** [comment]
I have the same problem on Windows 7 and KeePassXC 2.2.0. If I pause syncing in Dropbox settings, I can save the database without error.

**Comment by Trinkes** [comment]
Any update on this bug?

**Comment by phoerious** [comment]
We haven't yet found a solution, no. Windows is rather unforgiving with it's exclusive-access policy. *nix systems are easier.

**Comment by Trinkes** [comment]
After saving by pressing save fast, i wasn't able to open my db on mac. thankfully i was able to open it on windows and recreate it.

**Comment by wrmbaron** [comment]
KeepassX handles the situation without a problem. You might want to use the same strategy for saving.

**Comment by phoerious** [comment]
KeepassX doesn't support auto-reload and other features.
But Dropbox problems should be resolved in 2.3.0.

**Comment by gadams999** [comment]
Still happening with KeepassXC 2.3.1 (running as portable app -- from DropBox).  I resolved by disabling save safes at the moment.

**Comment by droidmonkey** [comment]
That is the fix... until the QSaveFile in Qt is pushed out
