### ISSUE TITLE
filename changed on Google Drive

### ISSUE THREAD

**Issue by kuntergunt** [keepassxreboot/keepassxc#6591]
## Overview
I have a keepass file on Google Drive which is mounted to my file system by Ubuntu Online Accounts. This is an online file system and no files are stored locally. When I make changes to this file with keepassxc it changes it's name to something like 184ll7faPVIYRO7eDN5DAc4cfjwZ4064a.
The old KeePass Password Safe that I am using currently does not have this issue.

## Steps to Reproduce
1. open file from Google Drive and make some change
2. close the file, keepassxc will save it
3. file seems gone, but another file shows up with a random name
4. after renaming the "other file" to it's previous name the content is all back and keepassxc can open it again...

## Expected Behavior
the filename should never change

## Actual Behavior
the file gets a different name without file extension

## Context
Keepassxc 2.6.4

Operating System: Linux
Desktop Env: Gnome 3.38.3
Windowing System: X11

**Comment by droidmonkey** [comment]
See #4856. This will be corrected by #6335

**Comment by rexmtorres** [comment]
2024 now and I still have this issue.  Currently using KeePassXC 2.7.9.  Interestingly, this happens only on my Linux system.  On Windows, it's completely fine.

**Comment by droidmonkey** [comment]
@rexmtorres use direct write saves when using linux GVFS... https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_save_options

**Comment by saadsidqui** [comment]
I have the same issue as @rexmtorres. While uaing direct save works, it exposes the database to corruption ... silently. That is not ideal and it might be worth exploring avenues to mitigate this issue for GVFS.

**Comment by droidmonkey** [comment]
> exposes the database to corruption ... silently

I'm not sure what you mean by that. Your risk of corruption is still incredibly small. You'd have to have a power outage or program fault during the milliseconds when data is actually being written to disk. It wouldn't be silent. 

Even if that did happen, you would have a recent version on Google drive you could restore. Or use the database backup feature we have.

**Comment by saadsidqui** [comment]
Ah, okay that makes more sense thank you. I must have misread the docs.
Thank you.
