### ISSUE TITLE
Application Menu dissapearing after a while

### ISSUE THREAD

**Issue by schiorean** [keepassxreboot/keepassxc#691]
## Expected Behavior
At any time when I open app main window and I hover the mouse over the title bar, application menu should appear. 

## Current Behavior
Right after the application is started it works. But after a while, if I maximize from tray the menu is not visible anymore when hovering the mouse over the title bar.

## Steps to Reproduce (for bugs)
1. Open application
2. Hover the title bar => you should see menu items appear
3. Close it to tray
4. Open from tray using "Toggle window"
5. Hover the title bar => now you shouldn't be able to see menu items

## Your Environment
* KeePassXC version/commit used: 2.2.0, AppImage
* Qt version (e.g. Qt 5.3): Qt 5.9.0
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Ubuntu 16.04.2 with default Unity.

**Comment by phoerious** [comment]
This issue is caused by a Unity bug and was fixed a long time ago in KeePassXC and also Qt itself. Can anyone confirm this regression?

**Comment by schiorean** [comment]
This issue is still present after upgrading to 2.2.1. Same Qt version as in original description of the issue. 

P.S. For me the bug was always present fixed in 2.2.0 too.

**Comment by droidmonkey** [comment]
this seems to be a qt issue based on the linked issue from phoerious.

**Comment by phoerious** [comment]
I get the feeling that not all Qt distributions ship the fix reliably. Especially Ubuntu seem to live up to their name and fuck things up consistently.

**Comment by phoerious** [comment]
Apparently, the issue does still exist, despite the Qt bug tracker saying it's been fixed.
