### ISSUE TITLE
Store a list of databases to whitelist/blacklist from SSI(Secret Service Integration)

### ISSUE THREAD

**Issue by hasezoey** [keepassxreboot/keepassxc#7916]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
This issue requests a whitelist / blacklist to set which databases to use / not use for SSI (without having to unlock them first)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I would like a Fourth field in the Settings -> SSI -> "Exposed database groups" list to that can be set to whitelist / blacklist of databases which would then be asked to be unlocked  on request
also as a side, if a whitelist / blacklist is adopted, a function to set new databases to either used / unused should be available

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Currently KeepassXC (version 2.7.0) asks to unlock *every* database when a SSI request is made, even though the databases would not contain any SSI groups

**Comment by droidmonkey** [comment]
Update to 2.7.1 this was fixed

**Comment by hasezoey** [comment]
> Update to 2.7.1 this was fixed

what exactly was fixed about this? i can seem to find a related change in the release (i am looking at https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.1)

also sorry but 2.7.1 is not available yet in my package manager (manjaro / pacman) i would like to not mess with the install currently

**Comment by droidmonkey** [comment]
Sorry this wasn't actually fixed. It is, however, captured by #7574

**Comment by hasezoey** [comment]
Duplicate of #7574
