### ISSUE TITLE
KeePassXC Not Respecting Gnome Dark Mode

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8050]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Window top bar appears white in gnome 42 dark mode.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC
2. Open KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window top bar should appear grey.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window top bar appears white.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: Gnome 42
Windowing System: Wayland

<img width="1440" alt="Screen Shot 2022-05-12 at 1 59 05 PM" src="https://user-images.githubusercontent.com/105461243/168168360-6f6f4830-723d-4841-89a4-126c48f05579.png">
d

**Comment by droidmonkey** [comment]
Appimage, snap, flatpak, or native install?

**Comment by ghost** [comment]
Native install

**Comment by vimpostor** [comment]
Related to #7817 (but not duplicate). To fix this issue we can simply perform a dbus query on startup (right now we are only using the Freedesktop Dbus API to detect runtime switches, as I thought Keepass's own detection was reliable enough to work on startup).

Edit: I see that only your window top bar is white, and the rest dark so perhaps Keepass detects the mode correctly after all and this is just a separate issue. Maybe this is a Qt or a Gnome bug, since Keepass uses server side decorations, so the drawing of the window header is done entirely by the compositor (in this case Gnome/Mutter).

It would be interesting to see if this problem also exists on Gnome+X11.

**Comment by droidmonkey** [comment]
True the top bar styling is actually owned by the compositor.

**Comment by vimpostor** [comment]
I think the upstream tracking issue is: https://gitlab.gnome.org/GNOME/mutter/-/issues/217

As usual, Gnome developers reject implementing this, because their ideology rejects the idea of server side decorations entirely, so I guess you would have to convince them to stop having such a narrow view of the world.

**Comment by droidmonkey** [comment]
There is a lot to unpack in that thread, am I right to assume this is a qt / gnome / wayland issue? I'm going to close this as there is nothing we can do about it.

**Comment by vimpostor** [comment]
> am I right to assume this is a qt / gnome / wayland issue?

Correct, it's a Gnome + Wayland issue.
~~I think this issue does not exist on Gnome + X11~~, so Wayland users could try switching to X11 as a workaround, after all this isn't the only thing that is not working on Wayland (e.g. see Autotype).

Also read:
- https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/
- https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html
- https://gitlab.gnome.org/GNOME/mutter/-/issues/217#note_357478

**Comment by ghost** [comment]
For the record this issue is still present on x11

**Comment by 4jNsY6fCVqZv** [comment]
I make the same observation on elementary OS 6.1. based on Ubuntu 20.04 with GTK3, where I have KeePassXC installed as the latest Flatpak.
Furthermore, I notice that the automatic change of the system to dark mode is accepted by KeePassXC, but as soon as I close KeePassXC and restart while the system remains in dark mode, KeePassXC restarts in light mode and thus no longer respects the system settings. Could you please fix both?

**Comment by vimpostor** [comment]
> Could you please fix both?

We can't fix the first one, as we don't draw the headerbar of the window. It is drawn by your compositor.
You will probably notice the same problem for all applications that use server side decorations. e.g. most Qt apps.

As for the second one, that is indeed something that should be working, as we manually inspect the style at startup, so it should just work: https://github.com/keepassxreboot/keepassxc/blob/a4d4adb1f61baf2bc447b4d5411497a3ef52aaaa/src/gui/osutils/nixutils/NixUtils.cpp#L89

But that should be a separate issue.

Edit: Actually it might be the same issue, since we use `QPalette::Window` which should be the color of the window frame.

**Comment by 4jNsY6fCVqZv** [comment]
Another observation is that on Fedora 37 with GNOME 43, the file chooser dialog in KeePassXC also does not support dark mode. Does this issue have the same background?

**Comment by droidmonkey** [comment]
File chooser is either native dialog to the desktop env or a qt dialog, which is rare. We don't handle that gui element.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your explanation. What does it take to solve this issue then?
Does KeePassXC support the native file chooser dialog of my mentioned desktop environment?

**Comment by droidmonkey** [comment]
That is tough to answer. To me it sounds like your system is not actually set to a dark theme or it is incompletely set.

**Comment by droidmonkey** [comment]
That is tough to answer. To me it sounds like your system is not actually set to a dark theme or it is incompletely set.

**Comment by 4jNsY6fCVqZv** [comment]
@vimpostor By now it works, both issues are solved for me!

**Comment by 4jNsY6fCVqZv** [comment]
> That is tough to answer. To me it sounds like your system is not actually set to a dark theme or it is incompletely set.

@droidmonkey How can I figure this out?

**Comment by droidmonkey** [comment]
Search the interwebs for similar situations? This isn't a problem on our end.

**Comment by 4jNsY6fCVqZv** [comment]
Checked again.
![Screenshot](https://user-images.githubusercontent.com/46536067/227231775-387f457a-d6cb-4f98-8467-a57280fd477b.png)
So far I had installed KeePassXC as RPM from the source fedoraproject.org. With this, the file chooser dialog does not respect the dark theme.
Now I have tried it with the Flatpak version from the source dl.flathub.org. Now when I am in the file chooser dialog, I see that the dark theme is respected.

What I notice is that it looks visually as if two different file chooser dialogs are being used here, depending on the version I have installed. Can this be?

And by visual I don't just mean that one time the dark theme is respected and one time it's not. The windows have different sizes and also a different position on the desktop where they are opened.

**Comment by vimpostor** [comment]
> What I notice is that it looks visually as if two different file chooser dialogs are being used here, depending on the version I have installed. Can this be?

This is because Qt will use the xdg-desktop-portal for file dialogs only in Flatpak by default. You can force xdg-desktop-portal outside of Flatpak by running KeepassXC with the following environment variable:

```bash
QT_QPA_PLATFORMTHEME=xdgdesktopportal keepassxc
```

**Comment by seb-maillard** [comment]
> You will probably notice the same problem for all applications that use server side decorations. e.g. most Qt apps.

I'm facing a similar issue after upgrading Ubuntu to 23.04 (Gnome version 44.0 + Wayland) from an old Ubuntu/Gnome version -I think 22.10/43, but I didn't pay attention before upgrading. I have version 2.7.4+dfsg.1-2 installed from the APT package.

I understand the ticket has been closed because top bar styling is handled by the compositor. However, I'd like to report that, contrary to @vimpostor's [comment](#issuecomment-1127705908), I haven't encountered this behavior with any other software -at least, so far.

In my case, both the top bar and the surrounding borders are painted white. Also, when resizing the window with the mouse, the pointer displays a really odd arrow. See below a screenshot vs. a native system window for reference.

![keepassxc](https://github.com/keepassxreboot/keepassxc/assets/33429284/2a19dce3-a6d9-4f9a-9967-bb34aa21d0d1)

![terminal](https://github.com/keepassxreboot/keepassxc/assets/33429284/a23a0c74-1c62-4b79-9e26-f3de823d2d0d)

**Comment by vimpostor** [comment]
> I haven't encountered this behavior with any other software

Then you are using only GTK software. The window border issue will appear with every Qt software. Gnome does not support server side decorations, so Qt will be forced to draw its own fallback client side decorations.

You could file a bug report for Qt to improve the fallback window decorations, but realistically you should go to the real source of the problem, i.e. Gnome and ask to implement support for SSD: https://gitlab.gnome.org/GNOME/mutter/-/issues/217

In any case, this is not KeepassXC's issue.

**Comment by dreua** [comment]
I don't know how but this is fixed, at least I couldn't reproduce in a Fedora 39 VM. (Needed manual switch do dark theme and a restart of keepassxc iirc.)
Now I just need to figure out how to fix that on my existing installation :thinking:

**Comment by mathmul** [comment]
For me it usually works on Ubuntu 24.0.4 / Gnome / Wayland and X11, but sometimes this happens and I just have to switch the theme back and forth. I have an a `theme` alias in .aliases that runs the following script:
```bash
#!/bin/bash

current_theme=$(dconf read /org/gnome/desktop/interface/gtk-theme)
echo "[.] Currently using ${current_theme}"

if [[ "$1" == "dark" ]]; then
	new_theme="Yaru-dark"
elif [[ "$1" == "light" ]]; then
	new_theme="Yaru-light"
elif [[ "${current_theme}" == "'Yaru-light'" ]]; then
	new_theme="Yaru-dark"
else
	new_theme="Yaru-light"
fi

if [[ "${new_theme}" == "Yaru-light" ]]; then
	new_color_scheme="prefer-light"
else
	new_color_scheme="prefer-dark"
fi

dconf write /org/gnome/desktop/interface/gtk-theme "'${new_theme}'"
dconf write /org/gnome/desktop/interface/icon-theme "'${new_theme}'"
dconf write /org/gnome/desktop/interface/cursor-theme "'${new_theme}'"
dconf write /org/gnome/desktop/interface/color-scheme "'${new_color_scheme}'"

# Alacritty
alacritty_config="$HOME/.config/alacritty/alacritty.toml"
if grep -q '#.*material_theme_light.toml' "$alacritty_config"; then
    # If the light theme is commented, uncomment it and comment the dark theme
    sed -i 's|#\(.*material_theme_light.toml\)|\1|' "$alacritty_config"
    sed -i 's|\(.*material_theme.toml\)|#\1|' "$alacritty_config"
else
    # Otherwise, comment the light theme and uncomment the dark theme
    sed -i 's|#\(.*material_theme.toml\)|\1|' "$alacritty_config"
    sed -i 's|\(.*material_theme_light.toml\)|#\1|' "$alacritty_config"
fi
touch $alacritty_config

echo "[✓] Theme changed to '${new_theme}'"
```

**Comment by seb-maillard** [comment]
Thanks for the tip @mathmul ! Unfortunately, I switched the theme back and forth using your script and it still doesn't work for me.

FYI I'm now running KeepassXC 2.7.8-1ppa1~mantic1 (from the APT package) with Ubuntu 24.04.1 LTS, Gnome 46 and Wayland. Dark mode for KeepassXC still looks the same as [before](#issuecomment-1580870129), i.e. with a white frame all around the window. Only difference is the cursor to resize the window, it looks slightly different now but still not like the default Gnome cursor:
![keepassxc_dark_mode_20241001](https://github.com/user-attachments/assets/b7c49b07-8e30-47bb-b955-2e348d7a40fd)

**Comment by mathmul** [comment]
Sorry I can't help you then @sebastien-maillard . My system seems to be the same as yours, only the keepassxc (installed via apt) version is different:
```shell
~ ‹main*› » apt-cache policy keepassxc
keepassxc:
  Installed: 2.7.9-1ppa1~noble1
  Candidate: 2.7.9-1ppa1~noble1
  Version table:
 *** 2.7.9-1ppa1~noble1 500
        500 https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
     2.7.6+dfsg.1-1build3 500
        500 http://si.archive.ubuntu.com/ubuntu noble/universe amd64 Packages
```

**Comment by seb-maillard** [comment]
Thanks for the feedabck @mathmul ! I installed v2.7.9-1ppa1~noble1 from KeypassXC's PPA accordingly but sadly it didn't solve the problem.
Not sure what differs between our two setups, but I guess there won't be a definitive solution until Qt improves fallback window decorations and/or Gnome implements support for SSD, as [suggested](#issuecomment-1581000164) by @vimpostor 

UPDATE: I just checked #11318 and this made me realize there's a `Theme` menu. I was using the `Automatic` setting. I switched it to `Dark` and, after restarting KeepassXC, I finally have dark window decorations, yippee!

**Comment by maurerle** [comment]
Nice finding - looking at the code, this can be only done once on GUI initialization:
https://github.com/keepassxreboot/keepassxc/blob/ed0ece304d423c6ba5040d3dd44544f9683e96ee/src/main.cpp#L131

While the user theme is not available yet but set directly afterwards when `interfaceThemeChanged` is triggered:

https://github.com/keepassxreboot/keepassxc/blob/80c1b9be6a09cee67411840ecde129bcab70ebe1/src/gui/Application.cpp#L132-L136

Eventually there is a way in Qt to repaint the window bar somehow without restarting, by setting its property directly..?

**Comment by mathmul** [comment]
@sebastien-maillard Oh, sorry, had I known you only need dark theme, I would tell you about the GUI option. I prefer light theme for everything during the day when it's bright, but I it switch to dark in the evenings and leave it so while the missus still sleeps in the morning.

*But* I forgot to switch to dark yesterday, and as it turns out opening KP (KeePassXC) first and then changing theme with my script didn't change KP theme, just like in your case. I've restarted my laptop in light theme for the second time to confirm, then again a third time, but I changed theme to dark before opening KP, and this time KP *did* open in dark theme and the switching with the script also works. Peculiar.

I will document here if I notice this behavior hypothesis is incorrect in the future, though I'm glad you've managed to achieve your goal.

**Comment by vimpostor** [comment]
Since Gnome keeps refusing to implement a server side decoration protocol, [Qt will now fallback to simulating Adwaita-like client-side decorations by default on Gnome Wayland](https://codereview.qt-project.org/c/qt/qtwayland/+/524641) and this issue as described originally (window title bar has wrong color) should be fixed with the [recently released Qt 6.8](https://doc.qt.io/qt-6/whatsnew68.html#wayland-client-on-linux).

**Comment by seb-maillard** [comment]
> I just have to switch the theme back and forth. I have an a `theme` alias in .aliases that runs the following script

By the way @mathmul, I noticed a weird bug recently on my laptop. When hovering some apps (e.g. Files, Settings), the size of the mouse cursor would suddenly increase and then go back to normal as soon as the cursor hovers a different area.
I eventually traced it back to your script. When switching between light and dark mode using the Settings UI, the values for the following keys actually never change and both remain `Yaru`, unlike in your script:
```
dconf write /org/gnome/desktop/interface/icon-theme "'${new_theme}'"
dconf write /org/gnome/desktop/interface/cursor-theme "'${new_theme}'"
```
Setting them back to the default value solved that issue :)

**Comment by BellavGFH** [comment]
> By the way [@mathmul](https://github.com/mathmul), I noticed a weird bug recently on my laptop. When hovering some apps (e.g. Files, Settings), the size of the mouse cursor would suddenly increase and then go back to normal as soon as the cursor hovers a different area.

As was mentioned before in this thread, it is not a bug. Just a different framework being used (than Gnome, looking at what you write?). Please note that the devs here do respond (kindly) to questions and remarks, different to the apparent Gnome SOP?

As for your remark specifically:

With some QT applications, the mouse pointer does not use the same theme as the default (e.g. GTK, xfce) desktop. This is especially clear is alternative cursor theme is installed. Being its own valid platform, QT do not use xfce/ GTK elements, thus falls back to its own default (e.g. similar to gnome's libadwaita?). However, QT does look at `$HOME/.icons/default` location for instruction. So to solve, create `$HOME/.icons/default/index.theme` and for example (for xfce) put in it:

```
[Icon Theme]
Inherits=xfce
```

After that, reboot to take effect.

**Comment by seb-maillard** [comment]
Thanks @BellavGFH for the feedback and the tip!

Actually, my comment [above](#issuecomment-2437719286) was referring specifically to a behavior of the dark/light mode switch **script** that @mathmul posted [above](https://github.com/keepassxreboot/keepassxc/issues/8050#issuecomment-2384930125). I only used his script once and reported the issue to him in this thread, but it's unrelated to KeepassXC! But the root cause is probably indeed connected to what you just described.

I switched back to using the standard Gnome dark/light mode switch—especially since it's now available as a quick action in the Power menu—and I don't encounter any weird behavior like the one I described about @mathmul's script 😊

As for the main issue reported in this thread that [also affects me](#issuecomment-1580870129), as of today—e.g. Ubuntu 25.10, Gnome 49 and KeepassXC 2.7.10—it's still not solved. I assume it won't be until the [solution](#issuecomment-1581000164) mentioned by @vimpostor is implemented on one side or the other.
