### ISSUE TITLE
Open URL (Ctrl+U) fails, due to missing escaping 

### ISSUE THREAD

**Issue by xshadow** [keepassxreboot/keepassxc#905]
## Expected Behavior
Open URL should open a URL in your designated browser

## Current Behavior
Nothing happens,  /usr/bin/xdg-open  $URL fails

Log Output:
 `Launch failed (/usr/bin/xdg-open https://trac.torproject.org)`

## Possible Solution
Escape URL's with  "" when passing to /usr/bin/xdg-open

## Steps to Reproduce (for bugs)
1.   Start Keepassxc
2.   open URL with STRG+U 
3.   nothing happens

## Context
Problems exists, when Starting keepass with `keepassxc` or `env QT_QPA_PLATFORMTHEME='' keepassxc` (mentioned as possible solution in https://github.com/keepassxreboot/keepassxc/issues/73 ) 

Does not matter which shell you uses, same behavior on bash or zsh. 

## Debug Info
KeePassXC - Version 2.2.0 - Snap Package
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16 
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by xshadow** [comment]
Solution mentioned in Ticket https://github.com/keepassxreboot/keepassxc/issues/418 and comment https://github.com/keepassxreboot/keepassxc/issues/418#issuecomment-298079422 does not solve the issue for me

**Comment by droidmonkey** [comment]
URL's are actually opened using standard Qt interface. There is not much we can (or want to) do about fixing this as replicating the Qt interface doesn't make much sense. The URL opening works everywhere except the snap. I actually think this is a bug in the snap distribution instead of a bug in escaping.

**Comment by xshadow** [comment]
I can confirm this issue is only present if you install keepassxc via snap. 

Install the following packages:  `apt-get install libqt5x11extras5  libykpers-1-1`

Download keepassxc and install it via dpkg using:

 `dpkg -i keepassxc_2.2.0-1_amd64_oldstable_jessie.deb`

Now everything should work as expected!

**Comment by droidmonkey** [comment]
I fixed it in the snap with my recent pr #1011 which will be out with 2.2.1

**Comment by xshadow** [comment]
Thank you!

**Comment by uusijani** [comment]
The issue persists for me in 2.2.1 in Ubuntu 16.04. I can get it to work by removing snad-xdg-open from snapcraft.yaml (effectively reverting [PR #1011](https://github.com/keepassxreboot/keepassxc/pull/1011)) before building the snap.

**Comment by droidmonkey** [comment]
@uusijani read the snap tips in the wiki

**Comment by uusijani** [comment]
@droidmonkey That page seems to have been deleted from the wiki, but I think I found the problem, sort of. I'm using the -proposed repository, where the current proposed snapd-xdg-open (2.28.5) is just a transitional package (pointing back to snapd), as [they've integrated xdg-open into snapd itself](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1723256/comments/2).

If I downgrade snapd-xdg-open back to 0.0.0~16.04 from -updates (which also requires a downgrade of snapd back to 2.27.5), the Open URL function in KeepassXC does work (with the fresh 2.2.2 release at least).

So an upcoming change in these packages will break this, unless they do some more juggling before the packages move from -proposed to -updates.

**Comment by phoerious** [comment]
The Snap tips have been moved to our FAQ. https://keepassxc.org/docs#faq-appsnap-run-appimage

**Comment by droidmonkey** [comment]
holy crap, can the snap guys figure out how to use their documentation...
