### ISSUE TITLE
Crash when deleting all entries of the history

### ISSUE THREAD

**Issue by Bleuzen** [keepassxreboot/keepassxc#938]
## Expected Behavior
It should not crash.

## Current Behavior
KeePassXC crashes.

## Possible Solution
--

## Steps to Reproduce (for bugs)

1. Open an entry
2. Click on "Verlauf" (History)
3. Click on "Alle löschen" (Delete all)
4. Click "Anwenden" (Apply) and than "OK"

## Context
I want to clear the history of an entry (an account). KeePassXC crashes when pressing "OK". Output:

```
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
libpng error: IDAT: chunk data is too large
libpng error: IDAT: chunk data is too large
libpng error: IDAT: chunk data is too large
libpng error: IDAT: chunk data is too large
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
Speicherzugriffsfehler
```

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Bibliotheken:
- Qt 5.9.1
- libgcrypt 1.8.1

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 4.13.1-1-MANJARO

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by louib** [comment]
Thanks for the bug report @Bleuzen 

I strongly believe this was fixed by #814, which will end up in 2.2.1.

In the meantime, you can see if you can reproduce using the `develop` branch (I was not able to reproduce myself using the latest version).

**Comment by Bleuzen** [comment]
@louib I built the current develop branch and still have this problem.

**Comment by louib** [comment]
@Bleuzen I just read the STR again, and I wasn't clicking on apply before clicking on OK. I'm able to reproduce now, I'll take a look a that.

**Comment by louib** [comment]
@Bleuzen actually, I just realized that the fix mentioned above was not upported to the `develop` branch. I just tested locally and it doesn't crash with the `release/2.2.1` branch. Can you validate that as well?

**Comment by Bleuzen** [comment]
@louib  I tryed it and it doesn't crash anymore. The fix seems to work.

**Comment by louib** [comment]
@Bleuzen awesome, I'll close this issue then.
