### ISSUE TITLE
Requires removal/insert of Yubikey at each unlock - Arch Linux

### ISSUE THREAD

**Issue by bunnybooboo** [keepassxreboot/keepassxc#961]
## Expected Behavior
In KeePassX there was the ability to keep the Yubikey in place in USB, and a physical touch of the button was all that was required. 

## Current Behavior
Now in KeePassXC every time the database locks I have to remove & insert the Yubikey to activate.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.12.13-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is fixed in an active pull request and will be released in 2.2.1.

**Comment by emelbardis** [comment]
Still happening to me on 2.3.1 in Fedora 27. Have to re-insert each time I want to re-unlock KeepassXC

**Comment by droidmonkey** [comment]
I'll look into it, but one thing we did not fix was releasing the yubikey after use. That is planned for 2.4 with support for multiple yubikeys.
